### ISSUE TITLE
add ISSUE_TEMPLATE.md

### ISSUE THREAD

**Issue by der-On** [X-Plane/XPlane2Blender#157]
https://help.github.com/articles/creating-an-issue-template-for-your-repository/

**Comment by tngreene** [comment]
### Blender Version
[[Version of Blender](https://docs.blender.org/manual/en/dev/editors/info/introduction.html#controls), such as '2.77', '2.78b' or '2.5-2.65']

### XPlane2Blender Version
[Blender User Preferences->Addons->Import-Export: Import/Export: XPlane->Version, formatted as '3.3.13']

### Brief Description of Problem

### Steps to Reproduce

### Attached files (optional)

**Comment by tngreene** [comment]
What else?

**Comment by bsupnik** [comment]
This is probably fine - your call.  For X-plane we have:
Expected Result
Actual Result
(We got this from Apple's bug reporter.)

I would also include some kind of note that we REALLY want attached .blend files for export problems.

**Comment by tngreene** [comment]
I decided I didn't like how GitHub use the text. It would be nice as a side bar to guide you, or a form to complete rather than text to edit.
