### ISSUE TITLE
Fix lit preview

### ISSUE THREAD

**Issue by der-On** [X-Plane/XPlane2Blender#169]
When I use the litFactor property to preview night textures, not only does it turn down the diffuse level of the material (good, I think), but it turns down the mix factor of my albedo map, which results in incorrect coloring of the night preview.  (WHY this happens, I'm not sure, but if I manually fix my diffuse map, it goes away.)

It looks like there's no impact on the OBJ export, so if we can find a way to set properties that keeps the preview correct, then this could be cool.

**Comment by tngreene** [comment]
The relevant code is in xplane_props.py

```
def updateMaterialLitPreview(self, context):
    texture, textureLit = xplane_helpers.getColorAndLitTextureSlots(context.material)

    if texture and textureLit:
        factor = context.material.xplane.litFactor

        texture.diffuse_color_factor = 1 - factor
        textureLit.emit_factor = factor
```

Perhaps the 3D Viewer's treatment of emit_factor and diffuse_color_factor is different than X-Plane. Without know what "manually fixed my diffuse map" means and what version of Blender this applies to and what "incorrect" means, I don't think there is much that can be done for this.
