### ISSUE TITLE
Some cockpit object attributes do not reset properly.

### ISSUE THREAD

**Issue by danklaue** [X-Plane/XPlane2Blender#184]
For instance, when I set one material to "Draw", it's not terminated, which causes all objects after it to be drawn, despite them being set not to "Draw"... or vice-versa.  This was already a problem in the previous version of this script, and required a workaround: duplicate the object with the desired attribute, to move its order in the stack up, delete the old duplicate, and you'd have a chance of getting it to work properly.

PLEASE make sure that all assignable attributes to any object (e.g. camera collision, draw, Polygon Offset, Alpha blend, LIT characteristics, etc.) are properly terminated, so as to not spill over into other objects' attributes upon export.

**Comment by bsupnik** [comment]
Hi Dan,

Could you please provide a small sample .blend file that exports incorrectly? We need a reproduction case for any attribute that is not reset; these files can then become standard test cases for the exporter itself so the bug stays fixed.

**Comment by danklaue** [comment]
[RV-10.zip](https://github.com/der-On/XPlane2Blender/files/264747/RV-10.zip)


Here's a trimmed down sample situation: an RV-10 with a cockpit object that consists of 5 cubes, each with a different attribute.  By default (i.e., without overriding weight), the exporter chooses an export order that I am not able to understand, but the situation becomes clear once you start overriding weights.

Here are some observations:

-The .blend file resides inside the "objects" folder, but the cockpit object is set to export to the top directory.

-There's a background panel, which is set to "Part of cockpit panel", and is textured with animated textures coming from the .acf file's 3D cockpit panel.

-Then there's a cube that's textured with a semi-transparent red texture representing a regular cockpit object, with no manipulator, no panel texture, no camera collision, or anything funky.

-Then there's a manipulator, set as a click-and drag for the barometer. It's set to not "draw".

-Then there's a cube with "Poly OS" set to 1,  that is offset and partially intersecting the visible, "normal" cube.  That way, you can see the effect of having the polygon offset set to 1 when you move the camera around.

-Next, there's a camera cage.


Where it gets interesting, is if you start messing with the weights. For example, if you set the camera cage object to have a weight of 1, you'll see attributes being applied to it that come from one or more of the previous objects.  

So the attributes assigned to these diverse objects ONLY apply correctly to the intended object, if you also actively manage the objects' weights... or, if you don't set any weights, by fluke, or by the order in which you've created each object.  

I.e, there's NO GUARANTEE that  an attribute that I assign to one object, does not spill over into other objects, as I continue working on the cockpit.

If you analyze the exported cockpit.obj file, you can see what's going on. An attribute is assigned to an object, based on the material settings.  But then, it is not always turned off before the next object is being drawn with its set of attributes.  Changing the weight changes the order in which a given object is drawn, and causes its attributes to spill onto the next object(s) that get exported.

**Comment by tngreene** [comment]
I think this was also closed by 29a091b. I tried playing around with the test file and the weights and such but it all seemed to work correctly. You can tell me otherwise
