### ISSUE TITLE
Export Error: with dupli groups

### ISSUE THREAD

**Issue by airfightergr** [X-Plane/XPlane2Blender#197]
Blender 2.77a/XPlane2Blender 3.3.11/MacOSX 10.9.5/Exporting to 10.50

I was successfully exporting my cockpit.obj, but suddenly I get an error during the export:
**_AttributeError: 'NoneType' object has no attribute 'objects'_**

Here is the xplane2blender.log and the error.txt with the error I get on the console.
[error.txt](https://github.com/der-On/XPlane2Blender/files/397741/error.txt)
[xplane2blender.log.txt](https://github.com/der-On/XPlane2Blender/files/397748/xplane2blender.log.txt)

Please tell me if you want any extra info or the file to check it.

**Comment by airfightergr** [comment]
More details...
The cockpit.obj is on Layer #1. On other layers i have other objects that export fine.
Here is the link for the .blend file: https://www.dropbox.com/s/ni5w634rhrt7tqh/avanti_cockpit_2.blend?dl=0

There is a possibility that I might have change something and I get that error. Since there are hundreds of objects, it is impossible to go through everyone without any clue what might be wrong.

**Comment by airfightergr** [comment]
I found the problem. I had 4 lights (airplane_panel_sp) group them, and in the objects properties, in one of the lights, the Duplication Group was on.

Set it to None...problem fixed.

**Comment by der-On** [comment]
This actually is a bug. The exporter should at least detect the unuported dupli groups.

**Comment by airfightergr** [comment]
If any extra info is needed please tell me so. Happy to help!

**Comment by brisnel** [comment]
I still have the error with looking a the log text

**Comment by tngreene** [comment]
Actually, I think the real bug is not that dupli groups aren't supported (but I don't really know how to use the feature). It think the bug is that it just doesn't handle well when no dupligroup is selected.

**Comment by tngreene** [comment]
Dupligroups are no longer a thing in 2.80. See #495 for more progress
