### ISSUE TITLE
Emissive materials from v3.2 no longer export as emissive in v3.3.

### ISSUE THREAD

**Issue by danklaue** [X-Plane/XPlane2Blender#220]
I've set the knobs in this example file to light up when the mouse scroll wheel plugin detects that the mouse is over that particular knob. I've used the "Emit" variable in Blender to assign this property to the knob, and it shows up in X-plane as intended.  Exporting it with the v3.3 script causes the emissive attribute to be lost.  It'd be very nice to have that back.

[HighlightsBrokenInv3.3.zip](https://github.com/der-On/XPlane2Blender/files/825795/HighlightsBrokenInv3.3.zip)

**Comment by tngreene** [comment]
`ATTR_emissive_rgb` was deprecated from X-Plane. Sorry it took this long to say this. If you're talking about some other use of `bpy.types.Material.emit` than this

```
# emission
                    #if mat.emit>0:
                    emission = [mat.emit*mat.diffuse_color[0],
                                mat.emit*mat.diffuse_color[1],
                                mat.emit*mat.diffuse_color[2]]
                    self.attributes['ATTR_emission_rgb'].setValue("%6.3f %6.3f %6.3f" % (emission[0], emission[1], emission[2]))
```

Let me know.
