### ISSUE TITLE
Optimize "remove duplicate verticies" optimization

### ISSUE THREAD

**Issue by tngreene** [X-Plane/XPlane2Blender#273]
There is a checkbox in the UI called Optimize which turns on a slow O(N^2) algorithm to remove duplicate vertices from the vertices table. It would be better to just have it be better preforming and remove the algorithm and checkbox.

Also: Is there anything else activated by this checkbox?

**Comment by danklaue** [comment]
Unless the export algorithm that removes duplicate vertices becomes very close to the same export speed as the previously "unoptimized" version, I'd prefer to have the option to export stuff unoptimized, as that really increases workflow speed.  Optimizing the mesh can be a final step before publishing, and it doesn't matter if it takes overnight to export it all.

**Comment by bsupnik** [comment]
@danklaue  The expected fix is that the optimization algorithm will be fixed so that it will not affect export time at all.

**Comment by tngreene** [comment]
From #433:

> 
> 
> I took the time to look into why exporting optimized objects is so absurdly slow. To get the idea how slow it is, first, just some numbers.
> 
> Exporting single mesh on a i7-6700HQ CPU @ 2.60GHz:
> Tris (#) 	Not-Optimized (s) 	Optimized (s)
> 1920 	>0.1 	4
> 7680 	0.1 	57
> 30720 	0.2 	1017
> 
> This is insane. I looked into the sources (I am not a python programmer) and It seems that the only thing it is doing is looking up duplicate vertices!
> Unfortunatelly it is implemented using the most naive method, it just traverses all the vertices for every single vertex! This results in time complexicity of O(n*n).
> It could be at worst reimplemented using some space partitioning technique yielding O(n * log(n)).
> 
> The blender's internal "remove doubles" operatior which seems to do pretty much the same do that for 30720 tris mesh in less than 0.1s compared to exporter's 1017s!

**Comment by tngreene** [comment]
This is almost closed. Now that we have the new pull request we can re-examine removing the optimize checkbox.

**Comment by tngreene** [comment]
I'm calling this closed. Removing the checkbox is a later discussion
