### ISSUE TITLE
Hide Scenery Properties when export type is Aircraft or Cockpit

### ISSUE THREAD

**Issue by tngreene** [X-Plane/XPlane2Blender#276]
In the layer settings should Slope Limit and Tilted be allowed for Aircraft and Cockpit exports? I have a hard time picturing how those types of scenery objects would be interacting with the ground.

**Comment by bsupnik** [comment]
No. SLope limit and tilted are _specific_ to scenery and scenery-instanced objects.

**Comment by tngreene** [comment]
Really the whole section of the UI labeled "Scenery Properties" needs to be hidden.
