### ISSUE TITLE
Duplicate manipulators lost when ATTR_cockpit changes

### ISSUE THREAD

**Issue by Colimata** [X-Plane/XPlane2Blender#295]
This is a nasty one that can cost a lot of time to the developer.
**Reproduction:**
Create an object (plane) assign layer, UV, material, ... and a manipulator. Good this object works.
If this object is then duplicated the new object gets exported but it's manipulator is lost. It's manipulator does not exist in the obj.
**Temporary solution:**
For the manipulator of the duplicated object, a slight change is needed. Even if only the tooltip text is slightly changed, the manipulator is back in the obj.
**Example file:**
[Lost_dataref.zip](https://github.com/der-On/XPlane2Blender/files/1227584/Lost_dataref.zip)
Created and last saved
blender 2.78c
exporter 3.4.0 beta 2

Generally, more possibilities for copying/duplicating x-plane data in blender would be very, very handy for professional projects. Say, copying HIDE animations of one object to another or simply copy/paste a manipulator. I'm sure that's really hard to do, maybe for a later release.

May a generally suggest staying in beta for quite some time. I'm sure there is some kind of timetable for the exporter release so that this is done. 
The thing is, for now, we are mostly detecting errors in combination with older files. But there could come out completely new bugs when we start to create complex files with 3.4.0 itself.

Best regards
Florian
COLIMATA

**Comment by tngreene** [comment]
It may be lost in the OBJ, but is it lost in X-Plane as well?

**Comment by Colimata** [comment]
Yes in X-Plane as well. The new manipulators are missing there, the object itself is there though.
This does not occur on every duplication, however, I haven't found a procedure that avoids it until now.
The file above is an example that is newly created with 3.4.0 beta 2 and shows this also.

**Comment by tngreene** [comment]
Notes So Far:
@Colimata, unless there is a specific part of the bug that deals with lost datarefs you're not telling me, I'm calling further test materials "lost_manip" instead.

My initial thought was that it was a dictionary key problem, however the true cause is much more complex.

Trace through the code
1. All the manipulators get collected from all objects (see ``xplane_primitive.py, collectManipulatorAttributes``)
2. First one gets written, added to the xplane_commands.written dictionary
3. When checking for a counterpart to reset the manipulator, the one previously written is found, causing it to be ignored. The relevant code is found at ``xplane_commands.py, getAttributeCounterParts, line 303-325 (especially line 325))
    
    # The pattern is a resetter or ONE of the setters.
    # Every other setter but us is a counterpart.
    if attr == resetter or compiledPattern.fullmatch(attr):
       allWritten = sorted(list(self.written.keys()))
       for oneWritten in allWritten:
           if compiledPattern.fullmatch(oneWritten):
               # We have to check for ourselves - we might be taking every written attribute
               # that is a SETTER that matches the reg-ex, e.g. we are ATTR_cockpit and we found
               # ATTR_cockpit|ATTR_cockpit_region.  So take ATTR_cockpit_region but NOT us.
               if oneWritten != attr:
                   found.append(oneWritten)
    
4. That first written manipulator is never removed from the manipulator
5. All next exactly duplicated manipulator does not pass
6. Something with slightly different value for a manipulator (such as a different tool tip) does pass canWriteAttribute, the entry in written is replaced, still no counter-part found, further exact duplicates will not get written

From the large block of notes at the top of the file

    Here's how the system works.  Conceptually any given attribute has one or more "counterparts" - other attributes that affect the same state vector.  For example, every ATTR_manip_xx command is a counter-part to every other one, and ATTR_hard, ATTR_no_hard, and ATTR_hard_deck are all counterparts.

    Amongst the set of counterparts, one is deemed the "resetter" - this is usually the one that sets X-Plane to the default state, and/or takes no arguments.  The other ones are "setters".

In self.reseters, the following is the relationship between the "setter" and "resetter"
            'ATTR_manip_(?!none)(?!wheel)(.*)':'ATTR_manip_none',

There is another note
  One known bug that I am aware of: X-Plane has interaction between manipulator and panel-texture state; the current exporter does not model this and the current authoring level blender data does not support it.  For the 3.4 release, we expect to leave things in their currently broken state; for 3.5, we can then add specific panel attribute labeling to the UI and have authors migrate their projects forward.

So, we know this:

There is one ATTR_manip, but not clearing of the manip when panel texture is turned on.

[295_lost_manip_objs.zip](https://github.com/der-On/XPlane2Blender/files/1252658/295_lost_manip_objs.zip)

**Comment by Colimata** [comment]
Thanks for the detailed explanation. I've found at least one cause that, if bypassed, does not show the error.
Now I don't have an overview of the working principles of the export system. But as for this code part and this issue of "losing manipulators" (and it's datarefs. values and descriptions), I think that in "xplane_commands.py" line 276 could be important. At least when I modified it the problem was solved.

Apparently, in this code section, it checks if this attr (Attribute) is already in "self.written". Now, normally it returns TRUE in line 275, allowing it to write the attribute.
But in the example case (duplicate object=duplicate Attributes) this does not work. Actually, this exact Attribute (Manipulator) HAS already been written to "self.written". Therefore in 277 it returns FALSE and excludes all the following manipulators (false duplicates for it) from being written to the file.

When I modified, line 277, from "return FALSE" to "return TRUE" (So no Attribute and manipulator get excluded at all), the test example worked, all 3 manipluators, it's dataref's and values are in the obj file.

I suggest adding more criteria in line 276 before it decides to exclude an attribute. But attributes alone do not seem to have some kind of ID associated. Using their names or values for our special case here is not enough since they are identical.
Maybe the case of ATTR_manip_..... could be excluded from this filtering generally? This procedure seems to be more for attributes like ATTR_cockpit and others.

Let me explain shortly why this case matters. Normally objects, and it's x-plane proprieties, in blender are duplicated AND MODIFIED. Those pass this filter, no problem. But in some cases, objects are just duplicated, placed, no other modification. Like the two "stearing wheel" manipulators for the nose wheels of pilot and copilot, or 3 transparent switches that switch on/off 3 mirrors in a cockpit with canopy, or two transparent switches that bring the viewpoint from the front seat to the backseat and vice versa.etc All those switches have manipulators with same dataref's, same values, even same description. 

Best regards
Florian
COLIMATA

**Comment by tngreene** [comment]
Also, I wanted to note this is *NOT* related to #293

**Comment by tngreene** [comment]
After some very extensive and detail-oriented testing across 3.20.13, 3.3.13, and 3.4.0-beta.1 (chosen in part because of how easy it was to make the old cases work again!) here are the results for the following test cases

## Materials

**[cockpit_panel_manip_tests.zip](https://github.com/der-On/XPlane2Blender/files/1261267/cockpit_panel_manip_tests.zip)**

## Explanation of outputs

### WRONG OUTPUT
ATTR_cockpit
ATTR_manip_xy ...
TRIS 0 36
ATTR_cockpit
TRIS 36 36
ATTR_cockpit
TRIS 72 36

each ATTR_cockpit is reseting manip, no ATTR_manip after

### CORRECT OUTPUT
ATTR_cockpit
ATTR_manip_xy ...
TRIS 0 36
ATTR_cockpit
ATTR_manip_xy ...
TRIS 36 36
ATTR_cockpit
ATTR_manip_xy ...
TRIS 72 36

correct cause ATTR_manip keeps getting turned on. Not optimal

### OPTIMAL OUTPUT
ATTR_cockpit
ATTR_manip_xy ...
TRIS 0 36
TRIS 36 36
TRIS 72 36

REALLY REALLY OPTIMAL OUTPUT
ATTR_cockpit
ATTR_manip_xy ...
TRIS 0 108  # for the win

### TEST CASES
1. 3 meshes, all cockpit texture, DIFFERENT manipulators for each
2. 3 meshes, all cockpit texture, SAME manipulator (this is the #295 test case)
3. 3 meshes, cockpit, no cockpit, cockpit, all 3 manipulators DIFFERENT
4. 3 meshes, cockpit, no cockpit, cockpit, all have SAME manipulator

Test |_3_20_13|_3_3_13|_3_4_0|Notes
-----|----------|--------|-------|---|
1|Correct?|Correct|Correct|3_20_13 writes ATTR_manip_none after every ATTR_manip_*
2|Wrong|Wrong|Wrong|All the same kind of wrong - lack of ATTR_manip after ATTR_no_cockpit. See also #295
3|Wrong|Correct?|Correct?|In 3_20_13, mesh starts with ATTR_no_cockpit, then ATTR_manip_delta, 3_3_13 and  3_4_0_beta_1 do not begin with ATTR_cockpit or ATTR_no_cockpit
4|Wrong|Wrong|Wrong|

**Comment by bsupnik** [comment]
FINDINGS:
1. Semantically the output is identical in all 3 of 3.20, 3.30, and 3.40 for ALL four test cases.
2. All three versions turn cockpit texture off and on unnecessarily when it is repeated.
3. All three versions fail to re-specify the panel manipulator after a cockpit texture change.

**Comment by tngreene** [comment]
So, resolution for this so far:

There is a real bug here: the trouble is that there may be a large swath of people relying on it for legacy planes. For 3.5.0 or 3.6.0 we can look at making a good fix and making a better way (or rather, a way at all) for artists to purposefully express "I want an unclickable glass display". Right now only an odd bug is letting them do this.

Until then you'll have to use some hacks such as
- Merging meshes when possible
- Changing the draw order the object (not sure how this works, ask Ben)
- Putting in more details in the tool tips, making them unique
- Adding spaces on the end of a tool tip

So, this isn't closed, but its not going in the 3.4.0 bucket unfortunatly.

**Comment by tngreene** [comment]
With the fix out overly ambitious ATTR reset, we have made progress on this bug! This is from the case `3_cockpit_same_manip`. As you can see it doesn't reset cockpit. So, the fix was fixing the attribute resetter rather than how sticky to make the manipulator.

```
# 0 ROOT
# 1 Empty: 3_cockpit_same_manip
# EMPTY: 3_cockpit_same_manip	weight: 0
	# 2 Mesh: 2_Plane
	# MESH: 2_Plane	weight: 0
	# MATERIAL: Cockpit_On
	ATTR_cockpit
	ATTR_manip_wrap	hand	0	0	0	0		2_manip_same
	TRIS	0 6
	# 2 Mesh: 2_Plane.001
	# MESH: 2_Plane.001	weight: 1
	# MATERIAL: Cockpit_On
	TRIS	6 6
	# 2 Mesh: 2_Plane.002
	# MESH: 2_Plane.002	weight: 2
	# MATERIAL: Cockpit_On
	TRIS	12 6

	ATTR_shiny_rat	0.5
	ATTR_no_cockpit
	TRIS	6 6
	# 2 Mesh: 4_Plane.005_on
	# MESH: 4_Plane.005_on	weight: 2
	# MATERIAL: Cockpit_On
	ATTR_cockpit
	TRIS	12 6

# Build with Blender 2.78 (sub 0) (build b'e92f235283'). Exported with XPlane2Blender 3.5.0-dev.0+40.NO_BUILD_NUMBR
```

vs old

```
# 0 ROOT
# 1 Object: 3_cockpit_same_manip
# EMPTY: 3_cockpit_same_manip	weight: 0
	# 2 Object: 2_Plane
	# PRIMITIVE: 2_Plane	weight: 1
	# MATERIAL: Cockpit_On
	ATTR_cockpit
	ATTR_manip_wrap	hand	0	0	0	0		2_manip_same
	TRIS	0 6
	# 2 Object: 2_Plane.001
	# PRIMITIVE: 2_Plane.001	weight: 1
	ATTR_no_cockpit
	# MATERIAL: Cockpit_On
	ATTR_cockpit
	TRIS	6 6
	# 2 Object: 2_Plane.002
	# PRIMITIVE: 2_Plane.002	weight: 1
	ATTR_no_cockpit
	# MATERIAL: Cockpit_On
	ATTR_cockpit
	TRIS	12 6

# Build with Blender 2.72 (sub 0) (build b'95182d1') Exported with XPlane2Blender 3.4.0
```

**Comment by tngreene** [comment]
I'm still not calling this one fixed, however. @Colimata, can you try the latest 3.5.0-rc.1 and see if it works for you?

**Comment by Colimata** [comment]
Hi. I have good news.
I did an hour-long test with all kinds of files, small number and a large number of objects. This seems to be solved. The duplicated objects got all the manipulators and attributes of the original objects and work error-free in X-Plane.

In the obj file itself, the code seems optimized. Meaning that the code line for a manipulator is reused multiple times for different objects. Impressive.

I hope another developer can confirm this.
By the way. The offline dataref search tool inside the dataref box is awesome.
Thanks for your work guys. Appreciated.

**Comment by tngreene** [comment]
Tried it myself, appears fixed. Yay!
