### ISSUE TITLE
"Drag Rotate" style datarefs aren't scroll enabled? (Mouse scroll wheel isn't configurable)

### ISSUE THREAD

**Issue by danklaue** [X-Plane/XPlane2Blender#359]
Not sure if this is an X-Plane OBJ8 definition limitation or if it's an XP2B limitation, but currently, I can't seem to enable scroll wheel support for "Drag Rotate" style manipulators.

When would I want to use them?  For example, for the pitch trim wheel.  A "Drag Rotate" manipulator would be ideal, as it would give the sense that you're really grabbing the edge of the trim wheel, and rotating it around its axis.  But I'd REALLY want to retain the ability to use the mouse's scroll wheel on the trim wheel... as it's such a great analog to the actual trim wheel.

**Comment by tngreene** [comment]
Thank you for bringing this to our attention! X-Plane's implementation was missing this support. There may be a fix for it soon, possibly for 11.25. When it is in, I'll make the UI for scroll wheels show up on Drag Rotate.

**Comment by tngreene** [comment]
@bsupnik What's the status on this? Is there a fix for this or something in the pipes?

**Comment by tngreene** [comment]
Moved to #621
