### ISSUE TITLE
Change "Draw Linked Objects" UI name

### ISSUE THREAD

**Issue by tkyler** [X-Plane/XPlane2Blender#393]
It looks like the option in the attached screenshot affects the ATTR_draw_disable property.  From a developer point of view, "linked objects" is not a term most are familiar with and it took me a while to figure it out(via the hint) as somehow I unchecked it during my workflow and nothing would draw :) Most devs refer to the developer wiki so the  nomenclature used there is best applied within blender also if possible.  SO.....I would request to alter this to checkbox (checkbox default to OFF) to read one of the options:

NOTE:  The hover-tip can be the same for any of the options below:
(hover tip:  "Applies ATTR_draw_disable to polygons.  All polygons with this material assigned will not be visible in X-Plane.  Great for manipulator polygons in the cockpit")

.....and the checkbox string description options:

| |  Disable Drawing  
| |  Disable Drawing of this Material
| |  ATTR_draw_disable
| |  Exclude from drawing
| |  Make polys invisible

I myself like, "Disable Drawing", with a good hover tip.

<img width="344" alt="draw_disable" src="https://user-images.githubusercontent.com/399085/46905130-e36ff300-ceb4-11e8-97c3-355b47d8e4ba.png">

**Comment by tngreene** [comment]
Fair point! Thank you for your constructive criticism! Linked is also a Blender term, which is weird. I'll think on it and pick from the list or a variation of it.

**Comment by tngreene** [comment]
1. `Draw Objects With This Material`
vs
2. `Draw Linked Objects`

1 has 31 characters, but even if cut off "Draw Objects" is still descriptive enough, 2 has 19 characters. Difference of 31-19 is 12 characters. I think it is worth it.

"Print Debug Info To Output, OBJ" is also long, but it works.

Next change I get to change it, I will!

- [ ] Change "Draw Linked Objects" to "Draw Objects With This Material"
- [ ] Update documentation

**Comment by tngreene** [comment]
Changed with 981585a10d7c
