### ISSUE TITLE
249: Convert Layer Groups to weights

### ISSUE THREAD

**Issue by der-On** [X-Plane/XPlane2Blender#40]

**Comment by tngreene** [comment]
What is this feature and was it ever completed for 3.2?

**Comment by bsupnik** [comment]
@alxunru Alex - can you do an export where layer groups are used to control ordering (like in 2.49) and see what happens please?

@tngreene If this is _not_ working, it's high prio and we'll have to decide if we want to shove it into 3.4.

**Comment by tngreene** [comment]
As far as I can tell, the previous way to use layer groups was to add an object to a group, and by carefully naming the groups, Prim's __cmp__ would use use the group name to put this in order.

```
class Prim:
...
    def __cmp__ (self,other):
            if self.layer_now != other.layer_now:					# LOD - highest prio, must be on outside
                return cmp(self.layer_now,other.layer_now)
            elif self.group != other.group:					# respect groups, then
                return cmp_grp(self.group,other.group) # compares names
...
```

Rather in modern XPlane2Blender we have weights. I'd much rather figure out the order they would have gone in and adjust the weight values than introduce Layer Groups as a new feature.

**Comment by tngreene** [comment]
This would be better covered in #441, since we don't even know if we want this or if Layer Groups should become weights.
