### ISSUE TITLE
280: Condense choices to control export of OBJs and Blender objects

### ISSUE THREAD

**Issue by tngreene** [X-Plane/XPlane2Blender#423]
Currently we have a number of ways to control whether or not an OBJ gets exported or not and whether or not a Blender object will be in it (or its children). These are not regular between Layers Mode (soon to be removed from #450) and Root Object mode (now known as Exportable Collection/Object, there are no separate modes).

Here is the current plan I'm thinking of:

## The OBJ will export if all the following are true....
1. Exportable Object/Exportable Collection is checked
2. Exportable Object/Exportable Collection is marked as ``Not Hidden In The Viewport``.
    - `Disable In Viewport` is not used (right now, but could be used later if people are trying to manage multiple View Layers and __that too__ gets to be an annoying amount of clicking).
    - If some artist has a need to export a Collection that is Hidden In The Viewport they could use `Exclude from View Layer` and `Not Hidden In The Viewport`. Gut feeling says that nobody needs to do this, so we would be unlikely to make this hack official
   
3. OBJ does not have errors

That way it would be easy to use Blender's built in UI to quickly control this and the exporter becomes more WYSIWYG.

By starting off only using `Hidden In The Viewport`` we can expand to using `Disable In Viewport` and `Enable If` as needed. If turns out to be a bad idea, there is nothing to do but remove a few lines of code, and we don't even need to change the updater.

## An object's mesh and ATTR_ commands will be excluded from the export if
1. It is ``Hidden In The Viewport`` (matching 2.79 Layers Mode (which should also have been in 2.79's Root Object's Mode))
2. It was collected via walking up via the #494 Split Animation feature (are we sure? Read #514)

Animations are always be exported.

(If you want to hide something and all it's children, you can hold shift while clicking the eyeball, no need for us to do anything like that for you.)

## Removed Properties
The "Include In Export" checkbox for the scene and the export_mesh (#409) property should be removed for being redundant.

**Comment by tngreene** [comment]
After having the alphas out for a while, some have brought up two facts:

1. Layers mode 2.79 was completely WYSIWYG in terms of show/hide ignoring meshes (and all other ATTR_ commands?). That's a bug for us. The fact that root objects was always missing this is also a problem. I think a detail this subtle needs to be kept in sync between them.
2. Manually syncing checkboxes and show/hide is potentially very annoying.

**Comment by tngreene** [comment]
To expand on "An object's mesh and ATTR_ commands will be excluded from the export if"

What is really implied is core philosophy of our exporter - to make the most optimized OBJs possible as smartly as possible

> "All attributes, animations, and other non-thing™ properties are exported unless removing them from the OBJ has no impact on how the OBJ looks in x-plane". This is a performance goal, not a correctness problem. - @bsupnik

**Comment by tngreene** [comment]
> Exportable Object/Exportable Collection is marked as Not Hidden In The Viewport. Disable In Viewport is not used

Actuallllyyyyyyy.......... Disable in Viewport matters! As found while trying to fix TestCase1, if the collection is disabled in viewport and exported, animation data is not reported correctly. In this case, Disabled In Viewport MUST be enabled or we aren't guarunteed to get the correct values.

However, individually disabling Blender Objects doesn't appear to have the same effects.

**Comment by tngreene** [comment]
Removing "Include In Export" and "Export Mesh" were removed in 9db6e25e75201dc

**Comment by tngreene** [comment]
Sorry, accidentally hit closed. Only a portion has been closed

**Comment by tngreene** [comment]
Closed with bc1ae7ca201e7. We can be sure about split-parent because that feature is export_animations_only for everything while walking up. Maybe we ought to have a unittest to be sure, but, not a high priority.

**Comment by arb65912** [comment]
Brilliant!!!! Great time saver Ted! Thank you!

**Comment by tngreene** [comment]
Not re-opening, but, I wanted to make sure that there were links all the relavent bugs that spawned from this one. Some of these are already mentioned
- #514 
- #536 
- #538
