### ISSUE TITLE
(ATTR|GLOBAL)_shadow_blend doesn't use material.xplane.blendRatio

### ISSUE THREAD

**Issue by tngreene** [X-Plane/XPlane2Blender#426]
Correctness bug: _shadow_blend doesn't let the user set .blendRatio for shadow blend. It simply exports
`ATTR_shadow_blend`
with nothing after it.

X-Plane has been using the default value `.5` this whole time and I guess nobody noticed or cared enough to file a bug.

**Comment by tngreene** [comment]
This would also be a good moment to make a blend mode unit test.

**Comment by kbrandwijk** [comment]
Looking into this, `.blendRatio` is specifically defined as 'Alpha cutoff ratio'. I'm not sure, based on the name and description of that property, if `blendRatio` should be used, or a separate `shadowBlendRatio` should be introduced?

**Comment by kbrandwijk** [comment]
Looking further, this would also impact the converter (see #455)

**Comment by tngreene** [comment]
I think we should reuse blendRatio instead of making a new property (we are extremely `new property averse` since they are very hard to cleanly remove).

- The ratio in `ATTR_no_blend <ratio>` and `ATTR_shadow_blend <ratio> ` represent the same range of values (0.0-1.0)`
- Artists are very unlikely to switch Blend Mode often and then re-assign `blendRatio`
- If I'm wrong and they do switch Blend Modes a lot, we can add this in later, and use the updater to copy to "Blend Mode is Shadow Blend + blendRatio" -> shadowBlendRatio

Another change, capitalize C and R in Alpha Cutoff Ratio. The name is good but we'll need to change the description based on Shadow Blend vs Alpha Cutoff.

**Comment by kbrandwijk** [comment]
I agree that they are so close together in functionality and meaning, and the blend modes being mutually exclusive of course, so reusing the prop makes sense indeed.

However, I could find a way to change the text that is shown in the textbox (that's just a parameter when you add it to the panel), but I couldn't figure out how to dynamically change the description (shown in the tooltip).

**Comment by tngreene** [comment]
I could have sworn you could have changed the tooltip. I guess not! Strange.

I care more about not changing the data model than not changing the UI.

the tool tip can be something general about how a Blend Ratio controls the output and we can have different labels beneath with the description we want. Will decide later, but I'm welcome to suggestions

**Comment by tngreene** [comment]
And, very small reminder to myself in the future, there's a TODO comment in xplane_249_material_converter that is set to be removed after this is finished.
