### ISSUE TITLE
ATTR_shadow/ATTR_no_shadow not implemented

### ISSUE THREAD

**Issue by tngreene** [X-Plane/XPlane2Blender#427]
ATTR_shadow and ATTR_no_shadow are not implemented. Related to #425, Mesh.FaceModes.SHADOW cannot fully transform with out it, and the artists are missing an important ATTR.

GLOBAL_no_shadow is controlled by an XPlaneLayer prop "shadow". There is no unit test covering this.

**Comment by tngreene** [comment]
Plan of Action
- [ ] Leave the GLOBAL_no_shadow in the XPlaneLayer settings, rename to "(Global) Cast No Shadows" with better tool tip
- [ ] Make per material property "cast_shadows", place below Blend Glass
- [ ] 2 errors GLOBAL_no_shadow and ATTR_shadow in the OBJ, ATTR_shadow and not scenery of any type
- [ ] Update the OBJ spec for this
- New property needs to be "Does this cast shadows?", Default is yes and resetter system has to know

**Comment by tngreene** [comment]
Docs are updated, no idea if they're really visible or not.

**Comment by arb65912** [comment]
Visible to , I mean main manual. Will check others in a minute

**Comment by arb65912** [comment]
Other links work as well!

**Comment by tngreene** [comment]
Thanks!

**Comment by tngreene** [comment]
Turns out the "The above may be affected" message is printing for everything.

_print_error_table needs to have that line
`logger.info("'Cast shadows' has been replaced by the Material's 'Cast Shado` Indented and only printed in the case of errors being printed.
