### ISSUE TITLE
Idea: Header directives should not be block level properties

### ISSUE THREAD

**Issue by tngreene** [X-Plane/XPlane2Blender#429]
# The Problem
@danklaue recently brought up again (as in #357) that having to ensure NORMAL_METALNESS is the same across every material in an OBJ or there will be an error is a massive pain:

- Copy and pasting materials between .blend files often does not line up
- It is hard to review the "Normal Metalness" setting across material datablocks quickly, or change them all quickly 
- Dumb error messages where 1 bad material is encountered first and taken as good then a ton of good materials are seen as bad and spew error messages out making debugging very time consuming
- It requires more and more duplicate materials to ensure the combinations necessary for certain header directives to be emitted, slowing down work

# Given Global Solutions
- [ ] Smarter error messages (assuming 99 "incorrect" objects vs 1 "correct" objects are probably reversed)
- [ ] Less log spam. We need grouping and summaries and cool formatting like manipulator animation requirements has
- [ ] More informative messages that help track down problem datablocks. Having "Currently working on Armature.001" then in 120 lines "Error: Material's foo property is above 30. Should be 10" is not helpful". Even mentioning the datablock name isn't totally that helpful at this point

Are all universal goals regardless of design decision here.

Dan's idea was an emergency escape override checkbox button to simply export NORMAL_METALNESS and disable checking each material is uniform - that at a certain point of complexity it is unreasonable to expect authors to do this work themselves for the Exporter's benefit.

Indeed, this fails the promise that you can scale up to a complex workflow easily and not be punished for it.

# Harder Design Problems
We have been pushing for XPlane2Blender to be easy to use correctly by design, for example forcing people to be organized to allow the exporter to make smart decisions, automatically selecting GLOBAL_ versions when appropriate, "Smart" manipulators that can take properties from Blender data and more.

I think these things have been a success, but, I haven't heard much feedback from the community either way. No news is good news? Dan has news: this sucks. That's one solid point, but certainly not the only one needed for a decision about the following statement:

**"Should all header directives be controlled by flags in the OBJ settings? Should there be override flags for power users for whom it is too difficult to force uniform layers?"**

Previously the answer was "We're reusing Blender's Textures per Material, Material's per Object", so, just be mindful. I wonder at what point is that too much to ask and how many opportunities for Material reuse artists are loseing because a copy for each combination in use has to be made.

**Comment by tngreene** [comment]
The obvious answer, of course is *"No, not all of them. But maybe some?"*

Here is a list of header directives that are controlled in places that aren't OBJ settings

## Exporter autochoses between GLOBAL_ or ATTR
Directive | Chosen for Header | Error if not uniform?
----------|-------------------|----------------------
"GLOBAL_cockpit_lit"  | "GLOBAL_" chosen if all material match     | No
"GLOBAL_no_blend"     | "GLOBAL_" chosen if all material match     | No
"GLOBAL_no_shadow"    | "GLOBAL_" chosen if all material match     | No
"GLOBAL_shadow_blend" | "GLOBAL_" chosen if all material match     | No
"GLOBAL_specular"     | "GLOBAL_" chosen if all material match     | No
"GLOBAL_tint"         | "GLOBAL_" chosen if all material match     | No
"NO_BLEND"            | If all material's Blend Mode are No Blend) | No

## Error If Setting Isn't The Same Across All Materials
Directive | Chosen for Header | Error if not uniform?
----------|-------------------|----------------------
"BLEND_GLASS"           | All material's Blend Glass must be True | Yes
"BUMP_LEVEL"            | All material's bump_level are same | Yes? Not sure on spec. Hasn't been implemented yet
"NORMAL_METALNESS"      | All material's Normal Metalness must be True | Yes
"SPECULAR"              | All material's specular intensity must be True | Yes
"TEXTURE"               | Can be autodetected, all material's must have same texture | Yes
"TEXTURE_DRAPED"        | Can be autodetected, all material's must have same texture | Yes
"TEXTURE_DRAPED_NORMAL" | Can be autodetected, all material's must have same texture | Yes
"TEXTURE_LIT"           | Can be autodetected, all material's must have same texture | Yes
"TEXTURE_NORMAL"        | Can be autodetected, all material's must have same texture | Yes

"TEXTURE_" has an override switch already, which was included for backwards compatibility reasons?

**Comment by tngreene** [comment]
There are three groups of problems of course:
1. "Why isn't my GLOBAL_ attribute being chosen?!" which is silent,
2. "Why is a GLOBAL_ attribute being chosen" isn't generally a problem unless there is a bug. "GLOBAL_" is always a win
3. "Why am I getting an error? They're all uniform I swear!" Que the single or hundred error messages

Having "GLOBAL_" being smartly chosen is very important to me because it meets up with 3 principles: "Hide the OBJ spec from the user to make it easier to learn", "Hide the OBJ spec from the user so they can't accidentally make a buggy or less efficient OBJ", and "Let the exporter take the details.

So, how bad is 1, 2, and 3?

**Comment by tngreene** [comment]
Also, how many materials does it generally take to drive someone insane trying to manually keep them all in sync?

I came up with another idea. "Right click on a material property, click make uniform, and an operator will find all the other materials in all the other OBJs it is used in and copy the current value to it. error solved. What about being shared between OBJs? .... we'll figure it out? Make a copy? Idk. See the GLOBAL_no_shadow update problem for more."

This is ergonomic, but doesn't solve the original problem: At a certain point, managing header properties via material datablocks is too hard for complex projects (for, at least, Dan's complex projects. Other community members are needed to check in here please).

**Comment by arb65912** [comment]
Unfortunately I am using maybe 30% of exporter abilities but it works for me (30% I mean)

Since Blender layer needs to have only one material to be properly exported, I select material I want for that  layer and simply use option "Paste material to others" meaning all other objects on a particular layer.

**Comment by tngreene** [comment]
# Plan of Action!
We are going to be moving GLOBAL_(cockpit_lit, tint), NORMAL_METALNES, and BLEND_GLASS, NO_BLEND to the Root Collections settings
- [ ] Add Data Model and UI (remember to show/hide based on export type as well)
- [ ] Unit test that these explicitly
- [ ] Code
    - [ ] We need updater code - for each root collection we see if any child Object has a material with the settings that would have caused pre-v4.1.0 rules to activate it. It doesn't have to be complicated, and for NORMAL_METALNESS and BLEND_GLASS if we see a checkbox, we'll say we're done. This isn't a large amount of fixing to do in the OBJ settings
    - [ ] xplane_material, material_utils, and xplane_header will all have a property to change, something much more simple now!

**Comment by tngreene** [comment]
Turns out GLOBAL_tint doesn't need the same kind of move - actually there is no check for which GLOBAL_tint being uniform I think it will just take whatever it finds first. GLOBAL_cockpit_lit is not in need of moving. 
So, we're ready I think!
