### ISSUE TITLE
Bad rotation when importing

### ISSUE THREAD

**Issue by legoboyvdlp** [X-Plane/XPlane2Blender#430]
When importing the AWX Dc3 into Blender, I get bad rotation on many objects - e.g. the ailerons:
![image](https://user-images.githubusercontent.com/10434911/59048557-f7ba9300-887d-11e9-9279-a3784b0257b7.png)

or flaps:
![image](https://user-images.githubusercontent.com/10434911/59048565-fee1a100-887d-11e9-8093-3d8263c06d61.png)

Is this an error in the importer or my fault?

I also get things like this:
![image](https://user-images.githubusercontent.com/10434911/59048689-4e27d180-887e-11e9-8d73-fafdee2f9aa5.png)

Where various objects are in the completely wrong place.

**Comment by tngreene** [comment]
This is a very interesting bug, mainly because XPlane2Blender doesn't have an importer. Are you talking about the (unreleased, highly unstable and use at your own risk not supported) converter? The 2.49 importer (no longer supported)? Something else?

**Comment by legoboyvdlp** [comment]
That's rather odd - I thought that was what the io_xplane2blender folder was meant to do? I put that in with my other Blender scripts and installed it as per normal...?

**Comment by tngreene** [comment]
io_xplane2blender is just the addon for XPlane2Blender (this addon). XPlane2Blender is not a name of some collection of X-Plane and Blender related scripts. Nothing should go in io_xplane2blender besides things related to this addon. Other scripts should also go in the scripts folder.

Where did you get the importer from?

**Comment by legoboyvdlp** [comment]
I downloaded the .zip file at https://github.com/X-Plane/XPlane2Blender/releases/, version 3.5.0.

**Comment by tngreene** [comment]
That zip file doesn't have any import related scripts in it, though

**Comment by legoboyvdlp** [comment]
I'm terribly sorry - I had forgotten that I had installed another importer. I really did think that it was this one...
I am actually using https://forums.x-plane.org/index.php?/files/file/38643-blender-importer/

Apologies for the trouble.

**Comment by tngreene** [comment]
No worries, I'm sure if you ask there you'll be able to get some help. Good luck!
