### ISSUE TITLE
Exporting optimized objects is ridiculously slow

### ISSUE THREAD

**Issue by dpospisil** [X-Plane/XPlane2Blender#433]
I took the time to look into why exporting optimized objects is so absurdly slow. To get the idea how slow it is, first, just some numbers.

Exporting single mesh on a i7-6700HQ CPU @ 2.60GHz:

Tris (#) | Not-Optimized (s) | Optimized (s)
------- | ---------------------- | ----------------
1920 | >0.1 | 4
7680 | 0.1 | 57
30720 | 0.2 | 1017

This is insane. I looked into the sources (I am not a python programmer) and It seems that the only thing it is doing is looking up duplicate vertices!
Unfortunatelly it is implemented using the most naive method, it just traverses all the vertices for every single vertex! This results in time complexicity of O(n*n).
It could be at worst reimplemented using some space partitioning technique yielding O(n * log(n)).

The blender's internal "remove doubles" operatior which seems to do pretty much the same do that for 30720 tris mesh in less than 0.1s compared to exporter's 1017s!

**Comment by tngreene** [comment]
Yes, you are entirely correct, the optimize method sucks terrible. #273 has talked about this before. The plan is to not even have an optimize checkbox and just have it be really really fast.

Thank you very very much for the profiling! I'm always searching for that information. I'm sorry there isn't a solution right now. The feature is simply very slow. I recommend using it only for the last step before you publish and distribute your OBJ.

I'll merge this with #273 for duplication, but again, thank you for the report and the profiling numbers.

**Comment by dpospisil** [comment]
Sorry for duplicating the issue, I have missed the original one.

Just to note, "Animation checking" can also take several minutes for complex objects with tons of animations. I don't know how fast is the blender python API but it seems to take too much time as well...

**Comment by tngreene** [comment]
Thanks for that too! We've been wondering "is it the vertices that are the killer? Or when there are too many animations? Or complex trees of animations?"

Would you be willing to download the [BD-5J Mircojet](https://forums.x-plane.org/index.php?/files/file/27269-bd-5j-microjet), turn on all layers and "Print Debug Info" and see how long it exports? This is the baseline test I've had everyone do.

Also, what OS are you using?
