### ISSUE TITLE
Xplane2Blender exporting only one side of obj texture

### ISSUE THREAD

**Issue by Paniczz** [X-Plane/XPlane2Blender#435]
First. I'm doing a project to make a video and i thought it would be cool to have my aircraft in xplane. So, i had a drawing in catia, long story short i now have everything in blender, and trying to export part by part showed me all files with textures have only 1 side texture, meaning a fuselage would only appear in planemaker the interior painted or the exterior, inside planemaker it will only show me one or another so there are parts that would be ok with, that show up with the texture that i made in the exterior, and others with only the interior. Don't know what to do guys please help! URGENT! I had to had this done by tomorrow!
![problem1](https://user-images.githubusercontent.com/52227296/60148135-49cc4580-97a6-11e9-9e47-e4d290f531e8.png)
![problem2](https://user-images.githubusercontent.com/52227296/60148136-49cc4580-97a6-11e9-8b7d-e5eb02bcbe57.png)

Has anybody ran into the same problem?

**Comment by airfightergr** [comment]
This is normal, if you haven't modeled the interior of the plane and for a very good reason. 

If you don't care to model the interior of the plane and you want to avoid the 1-side thing you might use the solidify modifier.

**Comment by tngreene** [comment]
Hi,

I'm extremely confused by your bug report, but apparently @airfightergr was pretty confident he understood it. Did his comment help?

If his comment was not helpful, I want to ask what version of XPlane2Blender and Blender you are using?

**Comment by Paniczz** [comment]
It worked i followed  @airfightergr counsel and it finally worked. Thanks a lot

**Comment by tngreene** [comment]
Great. I love it when a bug gets solved even when I have no idea what it was about. Huge thanks to @airfightergr, your help in supporting users is always appreciated and it is extremely valuable.

**Comment by Paniczz** [comment]
Again, can't enphasize how much you guys helped me. Thanks!
This is how it looked in the final project!
![image](https://user-images.githubusercontent.com/52227296/60298815-b6a82280-9901-11e9-8a70-810bdff004ff.png)

**Comment by tngreene** [comment]
Wonderful! Screenshots of finished projects make me very happy. But, again, all credit goes to @airfightergr for this save
