### ISSUE TITLE
Multiple types of blender animation

### ISSUE THREAD

**Issue by dwp7kp** [X-Plane/XPlane2Blender#438]
Hey I'm currently working on a project to produce a model of NASA's X-59 plane. Since this model is meant for supersonic travel, I wanted to add a variably sized nozzle to the exhaust. The best way I knew to animate this was through the use of a simpleDeform modifier to taper the vent in response to the afterburners. 

When I went to export this animation, no animation was transfer to the output file. I checked the logs and it seemed to be able to see my keyframes for the x-plane value, but not for my simpleDeform. I started to dig into your source code and I've come to the conclusion that non-translation/rotation animations cannot be exported. In my case, the FCurve for the deform modifier is not recognized as a valid group. I wanted to verify this and see if you knew of a possible work around.

I've attatched my log file. Let me know if I can provide any more info.

Thanks!

[log.txt](https://github.com/X-Plane/XPlane2Blender/files/3374518/log.txt)

**Comment by lehthanis** [comment]
You have to model and animate the individual variable exhaust nozzle leafs.  They usually overlap each other on the inner and outer radius and pivot independently.  Here's my T-38C VEN for example:
https://cdn.discordapp.com/attachments/504772531127975957/587362296100159509/NozzleAnim1.gif
https://cdn.discordapp.com/attachments/504772531127975957/587362551873011913/NozzleAnim2.gif

**Comment by dwp7kp** [comment]
Thanks for the quick response! That really helps. I was starting to think I'd have to settle for a non-animated one.
