### ISSUE TITLE
Concerned about state of xplane_mesh's API

### ISSUE THREAD

**Issue by tngreene** [X-Plane/XPlane2Blender#460]
As I am going through making the exporter work for 2.8, and looking at performance related code from pull requests (thank you @kbrandwijk) related to #347,  I am discovering that xplane_mesh's slowness is from potentially out dated and bad code.

This is especially a problem since this code contains some serious bottlenecks and hot paths:

Here are some of the code smells I've noticed:
- Unused and incorrect API like getTriangulatedFaces, getUVFaces, faceValues
- Old Blender API calls and needless checking for features of Blender. (Yes, everyone by now has BMesh!). See calling mesh.update(calc_tessface), then calling mesh.calc_tessfaces(). Seems unnecessary.
- Unpythonic code where extra copying and appending is done using listsoflistsoflists

As said in #459, I get the feeling that Blender could be doing the work of matching up faces and UVs much faster than us duplicating the work ourselves.

After the deduplicating algorithm the next hot spot is collectXPlaneObjects and `faceToTrianglesWithUV`.

`    # Converts a Blender face (3 or 4 sided) into one or two 3-sided faces together with the texture coordinates.`

Surely Blender has these data structures already lined up. I feel like we shouldn't have to zip this together ourselves. And in there, do we really not know if we're dealing with quads or triangles? Isn't looping through the *triangles* of a mesh's tessfaces going to give us *triangles*? Why the branch and dead code?

I've only glanced at this 2 or 3 times, but I really think there could be room for improvement. At the very least we can stop making temporary lists, copies, and using

```python
for i in range(len(faces)):
    my_face = faces[i] # Oh look, an index lookup we could avoid!
```

**Comment by kbrandwijk** [comment]
I agree, I definitely noticed some of this stuff, I wanted to keep the scope of previous changes minimal, so I'm glad you turned this into a separate issue. Also, I really don't have any performance figures other than my own machine, which is admittedly a bit much on steroids, so I can't really judge when something is really a performance issue, or 'just' a code smell.

**Comment by tngreene** [comment]
Yes. the annoying thing about Python is that it can be hard to turn a code smell into a performance boost.

Do you use PyVmMonitor and PyDev? It is a just a little rough, but you can get very detailed results! 
Here is v3-5's collectXPlaneObjects with Optimize on:
![image](https://user-images.githubusercontent.com/5393207/63350337-3d3e1680-c32b-11e9-9de9-7ff2c945c6f8.png)

Here is your de-duplication with optimize on.
![image](https://user-images.githubusercontent.com/5393207/63350201-f819e480-c32a-11e9-9412-1b28da59d585.png)

Honestly, I think we'll be able to remove the debug flag since it is so fast I doubt an artist will mind the .02 extra seconds - then everyone will be able to benefit without having to know what it does. Plus, shorter VT table, shorter load time in X-Plane!

Anyway, code smells.

**Comment by kbrandwijk** [comment]
My optimization doesn't smell ;) Great tools, didn't use them yet, but definitely will.

**Comment by tngreene** [comment]
Indeed it does not! I just meant to get back to talking about the bug instead of PyVmMonitor. Btw, if you download it, don't forget to purchase a license.

**Comment by tngreene** [comment]
Status update as I've been working away at the code base.

- [x] Remove getTriangulatedFaces, getUVFaces, and faceValues
- [x] Limited calls to calc_* calls
- [x] Code cleaned up and is more pythonic
- [x] Certainly MUCH work has been done on optimizing this tuff

Id say that we're cleaned up from all the concern's we've had!
