### ISSUE TITLE
How much do complex animations contribute to long export time?

### ISSUE THREAD

**Issue by tngreene** [X-Plane/XPlane2Blender#462]
Here's one made for you @kbrandwijk! So far all the focus on optimizations has been on the geometry gathering and and writing, and I think we can still work that down still. Something that hasn't been touched on is how long the animation code takes to run.

In my spreadsheet I've got some projects (no .blend file too look at so I'm just taking it on faith that the user had "a lot" of "complex" animations) that took longer than the BD-5J microjet but had less vertices.

Was it bad luck? Something their CPU didn't like? Cognitive bias? Some place where extra transformations are being applied when they shouldn't be?

I've never had time to make test blend cases of all kinds of combinations of nested animations, but maybe you will.

Check out `test_creation_helpers.py`, `tests/object/bone_configuration_*.py`,  and xplane_bone.py for some examples of how you code make some large complicated projects quickly. The code has been recently been very well commented as to how it works by Ben.

**Comment by tngreene** [comment]
Btw, @kbrandwijk, when I try to use the GitHub assign function or even the @ function and complete your name, it won't. I've noticed this with other people as well. Is it my browser or is this some account setting not to let people @ mention you? So far I've been typing it in manually

**Comment by kbrandwijk** [comment]
By default, Github restricts the mention autocomplete to project collaborators and thread participants. In this one, I'm neither. On one of my PRs, it works.

**Comment by tngreene** [comment]
Good to know, thanks!

**Comment by kbrandwijk** [comment]
I'm looking into this now. Currently, after the PR on the vertex/index write, the total processing time for the BD-5J is about 7.5 seconds on my machine. 4.5 seconds of that time if spent in one single place: `xplane_keyframe.__init__()`. So I agree that this is definitely the next place to start looking for improvements.

**Comment by tngreene** [comment]
Thought about it, not too interested unless it provided massive gains in performance and doesn't make the code difficult to understand or debug. Blender apparently doesn't like multithreading that much

**Comment by kbrandwijk** [comment]
As long as I'm still finding other huge gains, I won't look into it for now 👍

**Comment by kbrandwijk** [comment]
The two biggest candidates right now are:
- A superfluous frame_set call at the end of the keyframe processing. Doesn't have a single effect (the frame is set at the beginning of that method for each keyframe). However, it does account for 50% (!!!) of the total processing time of the animations (I shave another 2.5 seconds of the 7.5 total by removing it). PR incoming in a little while after I have confirmed my findings.

- The other big candidate is not moving frames at all, but strictly using the fcurve data, as that _already_ includes the translation, rotation and scale information, without the need to actually set the frame and read them from the object. Again, the main overhead here is setting frames, and being able to avoid that altogether will reduce animation processing time by 90%+.

**Comment by kbrandwijk** [comment]
I spent a good couple of hours on this particular piece (just the keyframe initialization). I can't squeeze any more out of it. The 50% optimization from #465 is about as good as it gets. The mandatory other frame_set call here is the bottleneck (it takes 99% of the remaining time), and out of our control.

The amount of animations and keyframes is the determining factor here. Not the amount of nesting, nor the amount of vertices. Afaic, this one can be closed for now after the PR is tested and merged.

**Comment by tngreene** [comment]
PR #465 is going to be merged for sure! Before beta.2 launches, when we finally merge lights back onto the main branch. This has been an extremely useful bug, thank you
