### ISSUE TITLE
280: Optimize breaks Blender 2.80

### ISSUE THREAD

**Issue by tngreene** [X-Plane/XPlane2Blender#485]
I decided to use Kim's optimization patch, but, maybe I copied it over incorrectly. Someone told me it broke when they tried to use it. Maybe I wasn't testing with it when I thought I did

**Comment by airfightergr** [comment]
Here is the terminal output
[Optimize_fail.txt](https://github.com/X-Plane/XPlane2Blender/files/3698998/Optimize_fail.txt)
