### ISSUE TITLE
how to specify relative path for textures?

### ISSUE THREAD

**Issue by muchimi** [X-Plane/XPlane2Blender#486]
Hi, I have a question which is probably very silly.

I'm learning the blender exporter after a long time with the 3DS Max tools and learning how to set things up.  I apologize if this has already been answered for 2.8.

How do I tell the exporter that the production textures are in a relative path from the .OBJ?
In this case, my textures are all going to be in  ../textures.

When I create the object, the textures are in a different folder from the .OBJ - usually in the same folder as this is how my project is organized.

When I export, I'd like the ../texture prefix to be appended to whatever texture file I provide in the root object properties.

What options do I use to tell the exporter to add a relative path to whatever texture name I provide?  My textures usually have albedo, lit and normal.

I see an option for the library prefix but not sure if that's the same thing - in my case I'm not creating a library.

I can edit the .obj manually of course - wondering how to do that from the plugin direct.

Thanks a bunch!

**Comment by muchimi** [comment]
I think I've answered my own question: just enter the prefix manually in each texture slot after disabling the "autodetect texture" slot?

**Comment by airfightergr** [comment]
Simplest way...
Click the file open icon

![texture1](https://user-images.githubusercontent.com/16308752/66372543-e8c02a80-e9ae-11e9-958f-6bcb13e6d819.png)

And then make sure that you have selected the Relative Path. Blender will do the rest for you.


![texture2](https://user-images.githubusercontent.com/16308752/66372544-e8c02a80-e9ae-11e9-84f3-391032323e41.png)

**Comment by muchimi** [comment]
Thanks.  I'm used to a slightly different system, I appreciate the feedback, it works.

**Comment by tngreene** [comment]
Glad it worked out! Thanks for the response @airfightergr!
