### ISSUE TITLE
Some say the "Must have a material" error is annoying...

### ISSUE THREAD

**Issue by tngreene** [X-Plane/XPlane2Blender#487]
Currently if you make a mesh with no material, you get an error. This can get annoying. Some people have proposed that the default Blender material and default XPlane2Blender material settings be used always.

My biggest question is "what happens if we later need to change the default XPlane2Blender material settings?" Make the updater make a material and give the old default?

What about EEVEE?

I'd want to know just how annoying of a problem this is. See also #429's idea (I think)

**Comment by arb65912** [comment]
Not annoying at all for me. Obviously each object has to have material assigned and it is user's responsibility.

**Comment by tngreene** [comment]
There is a solution I made in the developer panel for when I make a unit test and I want all my cubes and cones and planes to have the default Material - just to make it export. It isn't customizable, but it does make the "no material found" error go away quickly.

It could simply be moved from the (not that) hidden Plugin Development to the bottom of the scene settings.

Also an easy to implement option - copy the current object's 1st material to all objects that don't already have a Material. Customizable, but not obvious - like copying a property across many objects (blender function) or this idea (#467)

**Comment by tngreene** [comment]
Having recently done work on moving materials around the concept of a "default material" seems unappealing - another assumption to deal with and support. I'm much more in favor of the "Give the default material to everything" button we have now.

In a year no one else has complained about this, so, I'm going to close it for now. People who are curious can use the feature already and tell me what they think.
