### ISSUE TITLE
NORMAL_METALNESS in root object properties

### ISSUE THREAD

**Issue by muchimi** [X-Plane/XPlane2Blender#491]
One of the things I'm used to in the Max (Step2Sky) exporter is to set the NORMAL_METALNESS attribute directly at the root object level as a property of the object, not set in the object's material.

There is no deriving of materials/textures directly in Max - the textures are manually entered all the time on the root object which is a custom dummy object.   That's a box directly below the texture entries for the object being exported to an OBJ.  In fact in Blender, I use that workflow - create a dummy object as my root object, and then give it the textures to use for the x-plane .OBJ export including the attributes. 

In this manner, the NORMAL_METALNESS attribute is not different than specifying the layer, surface type, etc... attributes.

Currently in the Blender 2.8 exporter (and from what it looks like, older versions as well), that flag is set at the material level on the material property page associated with the object.  That makes sense if the object is exported using derived textures from the material and if using layers.

But I don't think it necessarily does when using root mode, and specifying manual textures (not automated).   As things stand right now, I have to  attach a material to my dummy root, and put the NORMAL_METALNESS flag on that material even when I manually specify textures which have nothing to do with the material being assigned.   However I shouldn't have to attach a material to a root object if the textures are manually specified.  Having to attach material just to get the NORMAL_METALNESS attribute seems an extra step and unnecessary as it serves no purpose outside of - having to do this extra step.  Sure it's not hard to do - I can create a dummy materials and share that with all my dummy root objects.

My feature request is to add a NORMAL_METALNESS checkbox directly to the object property panel, in the Textures box where the manual texture file names are specified.   It would only be visible if manual textures are specified (it wouldn't make sense to have that with derived textures from the material - because that would use the material's attribute).

Thank you for your consideration.

**Comment by tngreene** [comment]
The issue of where should `NORMAL_METALNESS` and `BLEND_GLASS` go has been talked about before, and I agree with your and other's view points. See #357 for more of the conversation. Thank you for adding your detailed experience as a user. This type of user story is very valuable to me - I'm glad you wrote it!
