### ISSUE TITLE
280: Ability to split parent-child animations across multiple OBJs

### ISSUE THREAD

**Issue by tngreene** [X-Plane/XPlane2Blender#494]
Use Case:

You want to make a complicated landing gear and wheel. The wheel is detailed enough to warrant its own texture.

Currently you have two choices:

1. Put the landing gear wheel in the same OBJ, so the wheel gets the animation - no separate `TEXTURE` directive for you
2. Make a duplicate landing gear, manually keep them in line, use Draw Disable but still have all the VT table to deal with

Here's a crazy idea we can do instead:

Put the Landing Gear and Wheel in separate exportable roots.

The XPlaneBone collection algorithm will, when it finds a mesh that has it's parent outside its current collection, recurse upwards and find every animation used (but not take the mesh)
In this way, both the landing gear OBJ and wheel OBJ's animations will line up.

## More Use Cases
- Landing Gear and Wheel, where the wheel has to follow the Landing Gear
- Organizing manipulators that share common animation
- Reducing the complexity of animated doors and cockpit manipulator handles
- Separating visuals and click spots in a cockpit
- I'm sure the community will think of more! Feel free to suggest

## Workflow Options
1. **Separate Collections For Each Split:** Place the landing gear in one exportable collection, the wheel in the other. Set the wheel's parent to the landing gear.
2. **Wheel is the child is in an exportable collection, also the child of something in an exportable object:** Place the landing gear in an exportable object, wheel in exportable collection. When the exportable collection is exported, the resulting OBJ has the wheel mesh and animation. When the exportable object is exported, the resulting OBJ has the landing gear and the wheel. This is weird, but, currently will be allowed. It wouldn't be very useful in the wheel and landing gear example.
3. **2 Exportable Collections with objects have a shared animated parent in any non-exporting anything:** The two collections will export and the shared parent will not
4. **Nested exportable collections:** This will error out before anything else will happen

Somewhat of a meta-case:
5. **Cube with an animated parent somewhere is in two exportable collections:** Both exportable collections should have the animation and Cube

**Comment by arb65912** [comment]
I am talking only from my experience on that.

I am used to having one UV map for gear and the tire plus other gear animated components exported via exporter.
All corresponding Bones and Objects are in the same collection (layer) and parenting is all done in that collection (layer).

No matter how detailed the gear is, one UV map 2046 or even 4k if needed is more than enough to make all details visible.

Having said that, personally for my workflow the "crazy" idea will not apply but maybe others will find it useful.

**Comment by tngreene** [comment]
This is a rough sketch of the algorithm
![Lookup_algorithm](https://user-images.githubusercontent.com/5393207/68051440-c4a9ed80-fcbd-11e9-82c5-3f53c04710b1.png)

**Comment by arb65912** [comment]
Ted, I had a case when I did not export properly and the case was like that.
Root object had bones with their children but there were also objects animated .
All under root object (empty in my case).
And s far as I remember the animated objects animations did not export or I got an error.
Someone told me that it was addressed but you did not release anything.
You would not release that as a temporary fix before getting beta ready?
Not pushing, just asking.
Thanks! AJ

**Comment by arb65912** [comment]
Hi Ted,
I tested the latest release beta 2 and had problems exporting cockpit manipulators.
I have sent you  email few days ago and also asked to confirm if you received but do answer from you.
I just want to make sure it has reached you so I am writing here.
Sorry to be  a pest...
AJ

**Comment by tngreene** [comment]
Since this bug mostly became about the workflow aspect of this, I am pleased to close this bug! Thanks (d43d646cea7cea06)!
