### ISSUE TITLE
280: Reconcile unit tester and object out of scene validation

### ISSUE THREAD

**Issue by tngreene** [X-Plane/XPlane2Blender#505]
In #411 we decided to warn and ignore instead of make an error for out of scene children (parsing up and down). This was OK, but I still rather feel it is an error. The trouble of making it an error is that it prevents the developer from easily making unit tests with multiple scenes. Unit tests run in no strict order, which means it cannot easily be made to test things in a deliberate manner to ensure the correct scene is being set. This makes lots of false positives for "child of out of current scene".

This is handy for organizational purposes and certain updater tests that need to test that it works across scenes.

So, I'm not sure. It isn't a big deal, but I don't like it. I think the test will be how many people write bug reports saying that they're not sure why something didn't export and the answer turns out to be

"Because you have a child object that is out of scene and you didn't read the warning. Because who reads the warnings anyway?"

**Comment by arb65912** [comment]
Despite the fact I do not understand many explanations here about code I DO read warnings anyway. :-)

Ted, when you have a chance, could you please write up a simple process of exporting 3 objects that are in different collections (as equivalent of version 2.79 layers)?

I still do not totally understand the concept of Root method export.

Thank you!

**Comment by tngreene** [comment]
I'm struggling to remember what the issue was with this, however, having recently made tests that involved setting the scene before hand, it wasn't that tedious to remember.

> Have every test case specify what scene it should be tested with if there are multiple scenes (tedious)

It was fine.

**Reconcile'd!**
