### ISSUE TITLE
Rename "Deck" in UI

### ISSUE THREAD

**Issue by tngreene** [X-Plane/XPlane2Blender#512]
As Ben explained:

> X-Plane has three-ish surface collision modes "No collide with Face (ATTR_no_hard)", "Collide with Face, face acts like an extension of the earth (ATTR_hard)", "Collide with face, face acts like a thin ~.5 meter barrier (ATTR_hard_deck).

Hard Deck was used initially for bridges where you want the bridge **deck** to be hard, but still have the ability to fly underneath the bridge. It also is useful for being able to land on hanger roofs but still be able to go inside.

"Deck" is a very confusing name for this in the UI: Unless you know the specific bridge case, that the top of a bridge is called its **deck**, then extrapolate that case to your case it makes no sense.

I instead propose "Only Slightly Thick" which is short, describes what happens to this surface behavior, and answer the next question "As opposed to..." better than "slightly thick" does.

**Comment by arb65912** [comment]
Ted, I could no find that property in Alpha 6. I will look again. Thanks! AJ

**Comment by tngreene** [comment]
Make sure surface type is set to something. It isn't a very well used feature - people who make bridges and hangers with platforms on top have a use for it.

**Comment by arb65912** [comment]
Thank you!
