### ISSUE TITLE
280: ATTR_ directives written for hidden objects

### ISSUE THREAD

**Issue by tngreene** [X-Plane/XPlane2Blender#514]
Current if Landing Gear has some material properties or other ATTRs, Wheel will get them too. I'm not sure how I feel about this. After all, if you want some material effect to cascade down to effect the children, you'll need it across your split parent too, right? And it would be much too difficult and defeat the purpose if you had to manually figure out what material properties and other ATTR_s to copy and paste to Wheel.

I don't know though. The goal was that "animations would be split across the two OBJs." We never talked about material properties.

**Comment by arb65912** [comment]
Just my opinion. I do not think there is a need to children objects materials needs to be inherited from a parent.

Gear and wheel are two separate objects and animations are linked but nothing else as far as material.
Most of the animations in my case are done using bones, bones and animated objects are in one collection, this is the simplest for me.

Of course I understand that others might like animations to be split across objects.
I just think that some features might cause more harm than good in overall picture.

Thank you Ted for continuous fantastic work on the exporter!

On a side note, I am using 2.80 exported for my current project and all works great (minus particles system mentioned by Ted but I did not test it yet)

**Comment by danklaue** [comment]
I agree. Material ATTR should not be inherited from parents. I use animations split across objects.

**Comment by tngreene** [comment]
So, to be more specific about what the bug is - the WYISWYG promise that ATTRs should not be written for hidden Objects is broken in several places right now. This makes this bug actually related to #538 , #536 , and #423.

Although I couldn't figure out what Material Properties ATTR_s can be written for not visible Objects right now - I did figure out 1 case `ATTR_manips`!

```
# 0 ROOT
	# 1 Mesh: thing_with_manipulator_split_parent
	ANIM_begin
	# translation keyframes
	ANIM_trans_begin	test
	ANIM_trans_key	0	0	0	0
	ANIM_trans_key	1	1.00474	0.86466002	-3.34055996
	ANIM_trans_end
	# MESH: thing_with_manipulator_split_parent	weight: 0
	ATTR_manip_drag_xy	hand	0	4.94999981	0	0	6.71999979	0			
		# 2 Mesh: child
		# MESH: child	weight: 1
		ATTR_manip_none
		# MATERIAL: Material.001
		ATTR_shiny_rat	0.5
		TRIS	0 372
	ANIM_end
```

I think the solution is to, during collection, set a "visible" flag - which takes into account subcollections it is contained in, default False and use that instead of complicated tests about export_animation_only and it's viewport status.

The rule, after all, is very simple. `Not Visible = Only ANIM_ allowed`
