### ISSUE TITLE
“Loop Animation Every” documentation issue

### ISSUE THREAD

**Issue by luweejinator** [X-Plane/XPlane2Blender#521]
can someone here better word the loop keyframe definition from the xplane2blender docs from the following;  
![A67C1F13-A5F1-47ED-A854-1412E81B828B](https://user-images.githubusercontent.com/59718474/72125614-13a77b00-331e-11ea-8a5a-d5cdf6094b80.png)

“[whatever]” ?

maybe a couple of examples to clear it up would be nice...

i love the rest of the script...
![BA43BEC4-0C22-4FDF-AC30-F4F2404CAE04](https://user-images.githubusercontent.com/59718474/72125777-b5c76300-331e-11ea-941e-b2a0c35ea1d5.png)

**Comment by tngreene** [comment]
Haha.... um.... yea that isn't well written. That [whatever] is supposed to link to actually good example. This one confused me too.

The BD-5J Microjet's Cockpit has a good example of using Keyframe Looping. This is how the Altitude gauges works.

```
	# rotation keyframes
	ANIM_rotate_begin	0	0	-1	sim/cockpit2/gauges/indicators/altitude_ft_pilot
	ANIM_rotate_key	0	0
	ANIM_rotate_key	250	90.00020741
	ANIM_rotate_key	500	179.99985474
	ANIM_rotate_key	750	270.00005532
	ANIM_rotate_key	1000	360.0002559
		ANIM_keyframe_loop	1000.0
	ANIM_rotate_end
```

A full rotation of the dial we're simulating is 1000ft, but the `altitude_ft_pilot` dataref can increase beyond that! We can't have an infinitely big gauge, so instead we say "every 1000.0 feet, loop back to the start of the animation".

Sometimes gauges like this also use clamping to prevent a dial from ever accidentally rotating backwards bellow 0. That I **did** write good docs about. See [here](https://developer.x-plane.com/article/all-about-clamping-animations/).

Search through some of the other airplanes in X-Plane for more examples. Did this explain it?

**Comment by luweejinator** [comment]
thats a much better piece of documentation!  thank you for that...
i have another question almost related to this...  i have seen some demonstrations pertaining to a “looping animation” in a slightly different light...  there are still datarefs and values being used that can be used with the term “looping” similarly in xp2b...  i researched this before a while back when i used a rotating piece on an E2-hawkeye...  using a sim/time/total_running_time_sec to animate the disc on the top of the plane...  when i applied the dataref tho,  i didnt use a bone to rotate it,  i set keyframes through the object properties instead of pose bone properties...  here i was able to change the endframe to 360 while setting keyframes at 0,90,180,270,360 respectivly and with frame 360 it repeated again starting at 1.  it was just that one primitive in its own .obj and without an armature bone...  this in plane maker shows it spins fine to 360 and then it goes in reverse back to 0...  in the game however it spins to 360 and starts over at 0 so it doesnt look like it did in plane maker,  but it actually works!
is it possible to toggle a “loop” lets say frames 1 to 10 that returns its frame value back to 1 when it reaches 10 and keeps proceeding 1 to 10 until a manipulator toggle switch from ruled cockpit obj connected to a different obj (that shares primitives with differentiating dataref ratio animations) that says stop spinning?  
an obj that contains several other moving parts with dataref animations varying in keyframe length can be handled yea, but i cant change the endframes from the default 250 without changing the rest of the objs endframes...
its also weird to me that i can set animations beyond the default 250 endframe setting without having to change the endframe value in blender...  example a knob that animates to frame 360 while the endframe (not keyframe) setting is still set to 250 and it still works in game...
sooo many loops i know...
for me;
currently int cockpit and ext cockpit values can only be set once each in plane maker...  int cockpit applies to cockpit object...  ext cockpit can be set to the cockpit object at the same time and was in my case until i wanted to add a “pilot”...  the workaround for me was to copy the panel objects and subtract its manipulators then set that copy as ext cockpit so this way you can see inside the cockpit without the pilot obstructing the view and have a visible and moving pilot from external view...  
the plan works so far but with some limitations...  i want the eyelids to blink on their own and loop blinking every couple o seconds or so...  while still held in the ext cockpit obj...
“loop”:  what and how...
...

“loop(s):” ?
i think i tried using custom sliders before...  im a little familiar with using the switch datarefs with the toggle manipulators to display the slider ratios 0 to 1, and 1 to 0,  is there a way to maybe set a frame with a second dataref that writes a switch toggle to 0 from 1, and 1 from 0?  so that lets say blink starts...  then blink reverses...  and just goes back and forth without having to use custom slider on and off with a key?  maybe a said key used as a toggle to enable or disable that “eyes” anim set?
thanks for the info on “loop animation every”...  
ideas tho...  kinda loopy?

**Comment by tngreene** [comment]
I'm sorry, I'm having a hard time understanding what your question(s) are vs what you've tried vs what you've seen vs.... other things. Can you refine your question(s) so they could be answered one at a time?

**Comment by luweejinator** [comment]
ok
yea that was kind of a combo...

1st question...  lets say i have a button, when i push this button i would like it to play an animation keyframed 1 to keyframed 11,
is there anything i need to do for it to animate 1 to 11 repeatedly?...  like looping 1-11, 1-11, 1-11, 1-11... by itself over and over,  until i push the button again?  (in which case it could stop, until pushed to...  start over at keyframe 1)...

2nd question
if said animation was functional is there a way to set a specific option on or off outside of a .sit file...  like default start set=on until you toggle it off?

**Comment by luweejinator** [comment]
reading back on it...  i could multiply the frames in blender creating one long repeated frameset by duplicating the keyframes into say the time it takes to empty fuel from full to near empty...soooo  i set a blink every 4 ish seconds...  so i could ~50gallons burned... (solve for avg time)...

(that avg time)/4 seconds

duplicate frames: 
(total blinking frames)*((that avg time)/4 seconds) 

= endframe total...  (maybe a lil extra for a margin for cruising?)

that might be a large anim frameset but i think it could work (total time running is a large ever increasing dataref,  whats one more like it?)

thank you for your time (:

**Comment by tngreene** [comment]
## Button
- (Optional) Mesh for the Visuals
- Mesh for the Push/Toggle/Whatever Works for you manipulator - the clickspot the user will press
- Manipulator fires a command, that will change a dataref for you (we'll call D because you didn't give a name)

## Some Kind Of Blinking Light
- Blender Keyframes define the rotation and location across time
- XPlane Keyframes that use the dataref D that changes when the command is fired by pressing the button

The I think about this is:

Dataref Value | Rotation Value
--------------|----------------
0.0 | 0
10.0 | 90
25.0 | 180
55.0 | 270

" When my dataref value is X, where do I want my Object do be?" and trust that X-Plane will make the animation look good inbe**tween** the gaps that aren't explicitly specified.

I didn't specify (for instance), what exactly should happen when my dataref value is 5.0 because I trust X-Plane will figure out to rotate it to 45 degrees.

So, don't think "how will my animation effect the dataref I've chosen", that is 100% incorrect. Also remember that you shouldn't have to do a massive amount of work. If you want an animation that takes place over the course of 10 seconds, you shouldn't need 10 X-Plane Keyframes and 10 Blender Keyframes to make it happen, unless the motion of your animation is really complicated and needs that much fine control. I've only seen that for things like landing gear.

The behavior (does it step over a range? Is it True or False? Does it increase forever?) and what a dataref represents in sim will of course impact how you use these tools.
 
Without seeing exactly what you're trying to make this is the best advice I can offer. If you get stuck or it seems like you're doing a lot of work when it feels like it should be more simple, e-mail me or make another bug report saying "How do I make this?"

**Comment by luweejinator** [comment]
how do i make a module that copies not only dataref values per selected, but primitive mesh position with dataref values as an array through frame duplications?
im trying to duplicate a selected armature bone animations into the next timeline data with shift+d #x frames...

—luijee lops joo

**Comment by tngreene** [comment]
What do you mean by module?

**Comment by luweejinator** [comment]
i ended up solving a little framestep mystery with using a different dataref...  i was trying to loop an objects frames with a f modifier graph editor cycle bake into a predefined time of sim desired,  and yea it didnt sound right because thats a LOT of frames...  i thought because there was a total sim time dataref that counted infinitly forward, that i could use it to count with frames and loop the count after a “loop animation every” term...  i didnt know if that loop animation every term was supposed to trigger a term specifying a endframe number, or a endframe time, or simply the amount of times it would loop after it completed its final set keyframes...  i thought maybe it would be useful to incorporate the graph editors factorial/exponential polynomial section to add to existing datarefs such as the total time  sec,  into extended count looping with a “module’s” set term like by adding further support into the polynomials equations; being able to click into the “forever range”, or allowing variables “literally” into the dataref values...  i think it might stretch into the “create your own dataref” section tho...  im pretty sure we dont want an “add dataref” AND a “create dataref”...  ....“module”?

**Comment by luweejinator** [comment]
a created dataref example might by like copying and modifying an existing one lets say lights_pulse dataref letting it count 0.000000 to 4 to 0.000000 instead of its original count of 0.000000 to 1.000000 to 0.000000

**Comment by tngreene** [comment]
Again, I'm having trouble following your train of though. Are you suggesting a feature, describing something you have tried or would like to try?

Some notes:

- XPlane2Blender is very simple, and uses only the regular Location/Rotations. We do not support the graph or curve editor, nor subframes, or really any fancy uses of polynomial curves.
- XPlane2Blender cannot create or change how datarefs work. Only Plugins and X-Plane itself can do that. XPlane2Blender allows people to pair a 3D model, Blender Location/Rotation Keyframes, and Dataref Keyframes and turn that into an OBJ. X-Plane uses that OBJ to display the model and animate it.

**Comment by arb65912** [comment]
Sorry for chipping in here but my personal opinion is to keep exporter simple and working properly rather than trying to make it very extensive which makes more room for errors.
JUst my 2 cents.

**Comment by tngreene** [comment]
Thanks @arb65912. XPlane2Blender will always lean towards simplicity, not only because we don't have the developer power to do anything crazy (😜) but also because it is the right philosophy.

**Comment by arb65912** [comment]
I have no doubts about developer power :-) and thank you Ted!

**Comment by luweejinator** [comment]
sounds like a plan.  (;

well that stuff makes sense,  there are so many options available in the xplane2blender package...  it would be nice to maybe disable the buttons that arent supported with the xplane interface...  maybe add an xplane editing mode in its own tab like some of the other defaults or custom ones... again so many options...  <3  —luijee

**Comment by luweejinator** [comment]
...  will there be any xplane2blender-like apps for xplane11 mobile?  {:

**Comment by tngreene** [comment]
Others have suggested a view for Blender that removes all buttons that are unrelated. I think it could be a good idea, but, features like that aren't high on my list of priorities.

Mobile decisions are not my department, but, I will say XPlane2Blender is used by the community and the company!

**Comment by luweejinator** [comment]
hey...  i have another suggestion for the xplane2blender...  while the export test result output to the xplane2blender log works great as it is...  can it turn those errors into hyperlinks to selecting the object it addresses...  so if say there was a missing material in say “primitive.001” ...  make “primitive.001” in the log a hyperlink,  so to click on the text named “primitive.001” straight from the log...  it then highlights object “primitive.001” in the 3d viewport and scrolls the outliner to“primitive.001” as well...  i know u could highlight and copy the text, and paste it into search outliner...  but a hyperlink sounds so much nicer...  iono...  bla  (;

**Comment by tngreene** [comment]
Being able to hyperlink to an object would be a neat idea. Unfortunately Blender has no way to do this. Nice thought though.

**Comment by luweejinator** [comment]
maybe blender doesnt have a way to create that but i’ll bet python might have a way to parse it...  how the exporter can single out and reorganize text to efficiency...  theres gotta be a program with similar ways of perhaps converting text to something like html or rich text...  notepad++ can change text color of certain terms...  how bout if it scans for the name tags and turns them into a targeted said name tag into the select function...  
or maybe adding another properties script button that shows the log output so you can leave the text window for notes and another window for the parsed error links...  ?  almost?
