### ISSUE TITLE
Material attributes such as "ATTR_shiny_rat" have weird defaults.

### ISSUE THREAD

**Issue by danklaue** [X-Plane/XPlane2Blender#524]
If you create a cube in Blender, using factory-reset values, and assign it a material, the default material seems to be created with the "Use Nodes" option enabled:
![image](https://user-images.githubusercontent.com/359923/72285875-a2abe000-3609-11ea-8c57-506eea4bc039.png)

This causes the exported file to have a default "ATTR_shiny_rat" of 0.5, but nowhere in the nodes is this value reflected.  I thought maybe the "specular" value could be set to 1, and have that affect "ATTR_shiny_rat", but that had no effect:

![image](https://user-images.githubusercontent.com/359923/72285986-d71f9c00-3609-11ea-9b01-106790c7a4c3.png)

I found that disabling the "Use Nodes" option reveals a non-node-based material, whose default specularity value is 0.5:

![image](https://user-images.githubusercontent.com/359923/72286030-f0284d00-3609-11ea-9c91-22578d33b4be.png)

And changing THAT to 1 ended up affecting the value for "ATTR_shiny_rat".

Quite unintuitive. I'd recommend hooking up the "ATTR_shiny_rat" value to something that more immediately ties in to the material type selected.  At this point I don't even know: IS there a way to control "ATTR_shiny_rat" if you're using node-based materials in Blender?

**Comment by danklaue** [comment]
What's more, if Blender is set to use the "Cycles" or "Workbench" renderer, rather than "Eevee", the above option to use nodes doesn't even appear.  
![image](https://user-images.githubusercontent.com/359923/72286361-a2f8ab00-360a-11ea-8f2e-a20ffaa100a3.png)

**Comment by tngreene** [comment]
We aren't actually using Nodes at all right now, it is a planned feature. If you turn off `Use Nodes` you'll see the `Specular` property that we do use, which does control the value of ATTR_shiny_rat.
