### ISSUE TITLE
Error Exporting OBJ.

### ISSUE THREAD

**Issue by drhugobr** [X-Plane/XPlane2Blender#532]
I'm working on a LIBRAIN mask OBJ file. (no texture applied)

its a simple cockpit object, when I try to export, I get the following error message:

  File "D:\xxxxxxx\xxxxxxxxxx\xxxxxxx\xxxxxxxx\objects\xxxxxxxxxxxxxxx.blend\Text", line 4
    bpy.ops.export-.xplane_obj()
                   ^
SyntaxError: invalid syntax

location: <unknown location>:-1

Python script failed, check the message in the system console

**Comment by tngreene** [comment]
That is extremely odd. Where did you get this copy of of XPlane2Blender, what version of it did you install, and have you made changes to the script yourself?

**Comment by drhugobr** [comment]
Hello Ted. I'm on the latest version from the git website. I've downloaded
it yesterday. Been using it in a couple of projects. But in this specific
blend file in getting this error.

Em qui, 30 de jan de 2020 12:50, tngreene <notifications@github.com>
escreveu:

**Comment by tngreene** [comment]
I see `\Text`. Was this part of a script you were writing in the Text Editor?

If so, then it makes more sense. You script has a syntax error.

**Comment by tngreene** [comment]
Compare
`bpy.ops.export-.xplane_obj()` with
`bpy.ops.export.xplane_obj()`

 You have a `-` between `export` and the `.`

**Comment by drhugobr** [comment]
Hadn't done any changes to the script. I'm just clicking the export button.

Em qui, 30 de jan de 2020 12:52, tngreene <notifications@github.com>
escreveu:

**Comment by tngreene** [comment]
Do you have any text files in the text editor?

**Comment by tngreene** [comment]
Specifically any text files named "Text"
![image](https://user-images.githubusercontent.com/5393207/73466161-773a2c80-434f-11ea-89aa-bd03822c95a6.png)

**Comment by drhugobr** [comment]
you where right about the "-", there was a "-" added by accident in the button we use to export, (its just a button that we click to export from anywhere in blender.

**Comment by tngreene** [comment]
Glad it all worked out :) File another bug if you ever have more problems or questions.
