### ISSUE TITLE
Blender 2.79 Which X-Plane2Blender to use?

### ISSUE THREAD

**Issue by TheArtfulPlonker** [X-Plane/XPlane2Blender#535]
Hi,
I am really struggling to get x-plane2blender to work with blender 2.79 I have used many variants of the plugin and can’t seem to get it to work. I was just wondering if you new if blender 2.79 works with it and if so how and which version to use.
Many Thanks,
TheArtfulPlonker

**Comment by airfightergr** [comment]
https://github.com/X-Plane/XPlane2Blender/releases/tag/v3.5.0-rc.1

**Comment by TheArtfulPlonker** [comment]
nope not working just says it produced a lot of errors! and then it doesnt show up in the folder i set it to go to
Also i have tried 3.5.0rc1 before doesn't work for me

**Comment by airfightergr** [comment]
I've made a video couple years ago with the basics. Might help you.
https://www.youtube.com/watch?v=-mvQDVg7Uy0

**Comment by TheArtfulPlonker** [comment]
ok thanks will check it out

**Comment by tngreene** [comment]
Thank you @airfightergr for the support assist!

@TheArtfulPlonker Have you been able to install the addon? Blender 2.80 and XPlane2Blender > 4.0.0 has been quite stable. Is there a reason you want to use Blender 2.79? Regardless, the steps are still the same in each. The UI just looks a little different.

**Comment by TheArtfulPlonker** [comment]
it doesnt work on both for me i really like 2.8 but i had a little scare when i moved and got stuck so i don't want to loose all my work again!

**Comment by tngreene** [comment]
What exact link are you using to downloading?

When you say "doesn't work" do you mean "Blender crashes", "XPlane2Blender doesn't appear in the UI", "it crashes", "a big scary bubble filled with text appears?"

**Comment by TheArtfulPlonker** [comment]
When I say it doesn’t work I mean it says that it produced a lot of errors and doesn’t show up in the directory I put it in

**Comment by TheArtfulPlonker** [comment]
I am using 3.5.0rc1 it is installed correctly just doesn’t want to export. And I have watched the video it was quite a good help followed it but didn’t make a difference sorry

**Comment by tngreene** [comment]
It would really help to work on your case if you were more specific. When you say "doesn't want to export" can you describe what you see? Can you include a screenshot of what concerns you or you thinks is an error?

**Comment by TheArtfulPlonker** [comment]
Yeah will tonight

**Comment by TheArtfulPlonker** [comment]
![image](https://user-images.githubusercontent.com/59488892/74978072-cdb4fb00-5423-11ea-8f8d-00e65508a0cd.png)
It says this and then doesnt show up in the directory i put it under

**Comment by TheArtfulPlonker** [comment]
But then doesnt say anything is wrong in the text file!

**Comment by tngreene** [comment]
A .blend1 file is a backup copy of the current .blend file Blender makes, you can ignore it.

You do not get a .obj file if there are errors. The popup bubble tells you your next step to do - **Look in the internal text file XPlane2Blender.log**

What does it say? If you don't know how to find this the video shows how to see it. Make an area of the Blender UI be the Text Editor and select that file

**Comment by TheArtfulPlonker** [comment]
![image](https://user-images.githubusercontent.com/59488892/75097131-26f56980-559f-11ea-962c-34a6817511b4.png)
What does this means i have followed the xp2blender log scripts

**Comment by TheArtfulPlonker** [comment]
I looked in the xp2blender log there is nothing!

**Comment by TheArtfulPlonker** [comment]
I have fixed all of my problems thanks for your help guys!

**Comment by Denzy7** [comment]
> I have fixed all of my problems thanks for your help guys!

How you fix it?
