### ISSUE TITLE
blender 2.8 multiple objects in one export file

### ISSUE THREAD

**Issue by subabrain** [X-Plane/XPlane2Blender#537]
i tried to get more objects (meshes) in one export file - but i didnt get it - maybe you could help.

it only make seperate export files ...

thanks a lot!

**Comment by tngreene** [comment]
Can you post a screenshot of the outliner? Are you using Exportable Collections or Exportable Objects to collect your meshes together?

**Comment by tngreene** [comment]
Something with this kind of information
![image](https://user-images.githubusercontent.com/5393207/75170301-e3fad980-56f7-11ea-816f-499f2c40d67e.png)

Here is the outliner clearly showing what meshes are in what collections, and in the Scene settings, you can see which of my collections are marked as exportable and which are not.

The actual content doesn't matter, I'm sure your project is very different from my example, and if you aren't using Collections like this, then please somehow highlight or write down which Objects (probably empties or armatures) are the Exportable Objects.

**Comment by subabrain** [comment]
thanks - but i got it - i put all in one collection - but theres one question - how can i sperate (export) textures on multiple meshes? Thanks a Lot!

**Comment by tngreene** [comment]
Each OBJ can have one texture file (and one night time version and normal map, etc). If you want to have multiple meshes share it, UV unwrap each and use a small segment of the texture file. Checkout some of the texture files of the existing laminar research planes and objects and art assets - you can see how everything gets packed in to one file.

See also the [BD-5J Microjet](https://forums.x-plane.org/index.php?/files/file/27269-bd-5j-microjet), which is a complete example project.

**Comment by tngreene** [comment]
@subabrain are you all set?

**Comment by subabrain** [comment]
ok i understand - now i made one uvmap for the whole objects in blender - now its working - thanks a lot!

**Comment by tngreene** [comment]
Awesome! Send in bugs and problems as you find them!
