### ISSUE TITLE
Import option missing

### ISSUE THREAD

**Issue by Krahazik** [X-Plane/XPlane2Blender#539]
Based on the description and titles I was expecting to be able to import x-plane files into Blender addition to exporting from Blender. But so far I can not find any import option at all. In the Export menu there is a listing for X-Plane Object, but there are no such items or options within the import menu or any where else that I can find.

**Comment by tngreene** [comment]
One day, maybe.

From the README at the top

# Introduction

This addon for Blender 2.79 and up makes it possible to export models made in Blender to the X-Plane object format (.obj). **Despite the name "XPlane2Blender", there is no import feature.**
