### ISSUE TITLE
XPlane2Blender not working

### ISSUE THREAD

**Issue by Kutimy** [X-Plane/XPlane2Blender#540]
Hi everyone. I am not an expert user of Blender, although I do frequently use other 3D software, I have been told about the advantages of Blender and I am ready to learn. Right now I need to export some Blender files to XPlane .obj and I just downloaded io_xplane2blender_3_5_0-rc_1-40_20181016150257.zip and installed it following the instructions. But I find that when trying to export the file, it does nothing and the Blender addons installer presents these messages: attached screen copy and system information.
Thanks for help.

**Comment by Kutimy** [comment]
UPS! Please, find attached files.
![BLENDER-SCREENSHOT](https://user-images.githubusercontent.com/61830197/75979302-7b261500-5ee0-11ea-9def-8f15fde19063.JPG)
[system-info.txt](https://github.com/X-Plane/XPlane2Blender/files/4292754/system-info.txt)

**Comment by wodecffb** [comment]
You use the wrong  Plug-in version

**Comment by Kutimy** [comment]
Please, what is the correct version and where is it?

**Comment by arb65912** [comment]
https://github.com/X-Plane/XPlane2Blender/releases/tag/v4.0.0-alpha.6

Enjoy!

**Comment by Kutimy** [comment]
Thanks arb65912. As it didn't work, I uninstalled and cleaned the system and the windows registry. I did a clean installation of Blender 2.82-W64, I installed the plugin again but it continues doing nothing at all. I can export it to .stl and use the model in other software, but it doesn't export to XPlane.obj ... 
![Captura](https://user-images.githubusercontent.com/61830197/76080151-93606780-5fa6-11ea-86d1-0bcee12974d0.JPG)

Could something be missing to install on the system?

**Comment by arb65912** [comment]
Hello, try to read and apply rules Ted is describing.
It has to something simple with installation or setup.
Do any dialog boxes show X-Plane related menu?
If not than I guess it is just wrong installation.
Where did you install blender and addons? 
XPlane2Blender folder needs to be in plugins folder but I am not sure if it can be in AppData folder.
Maybe Ted will chip in here.
I am almost sure it is the way you installed it.
