### ISSUE TITLE
Animation don't export in Blender 2.82 and 2.79 too (Xubuntu 19.04)

### ISSUE THREAD

**Issue by AllHafRA** [X-Plane/XPlane2Blender#541]
Hi! A little more and I'll lose my mind. I used Xubuntu 19.04 64 bit, Blender 2.82 (build b'77d23b0bd76f ') and xplane2blender 4.0.0-alpha.6 + 75.20200221193248. I create a mesh, make a simple animation (for the test) with movement from one point to another with key frames from 0 to 100 frames, set up the material, prescribe dataref, its value (it changes in the screenshot). Animation works in blender, the file is exported without errors, but if we open .obj with a text editor, we will understand that the animation was not registered. When adding a file to Plane maker, of course, I do not observe any animation either.
If you manually register the animation in the .obj file, for example, this fragment, then everything is perfectly animated in plane maker. No bones are needed for this, although I tried with them too, export animation in Blender 2.79 with xplane2blender 3.5 don't working too ! 
"ANIM_begin
ANIM_trans -13.3000000 0.280000 21.800000 -13.300000 0.280000 21.800000 0.000000 0.000000 none
ANIM_rotate_begin 0.070000 -0.0200000 0.990000 sim / flightmodel2 / controls / flap_handle_deploy_ratio
ANIM_rotate_key -20.000000 1.500000
ANIM_rotate_key -15.000000 1.500000
ANIM_rotate_key -6.000000 0.000000
ANIM_rotate_key 0.000000 -2.000000
ANIM_rotate_key 15.000000 -4.000000
ANIM_rotate_key 20.000000 -4.000000
ANIM_rotate_end
ANIM_trans -13.3000000 0.280000 21.800000 -13.300000 0.280000 21.800000 0.000000 0.000000 none
TRIS 0 36
ANIM_end "

Please help solve this oddity - my project is being delayed ...

![Снимок экрана_2020-03-07_18-03-18](https://user-images.githubusercontent.com/61907057/76143300-963f8300-60a0-11ea-84bd-8ce1a891dc61.png)
![Снимок экрана_2020-03-07_18-02-53](https://user-images.githubusercontent.com/61907057/76143301-9770b000-60a0-11ea-8b49-46902c729cae.png)
![1](https://user-images.githubusercontent.com/61907057/76143302-9770b000-60a0-11ea-89be-cd2ad884b1ab.png)

**Comment by tngreene** [comment]
Can you send me the most simple version of your project to me in a zip file? It can be here or privately in an e-mail to ted@x-plane.com
