### ISSUE TITLE
Datarefs Not Reading/Saving Properly

### ISSUE THREAD

**Issue by ArcticCoder1** [X-Plane/XPlane2Blender#547]
I know these issues existed before, but they're happening in the [v4 beta](https://github.com/X-Plane/XPlane2Blender/releases/tag/v4.0.0-beta.1), even though they are "fixed". (#194 | #225 )

My older blender files previously opened with Blender 2.79 contain these X-Plane Datarefs within the dope sheets, but not within the object properties. Any new datarefs changed on these older objects do not transfer into the exported .obj file as the older datarefs overwrite them, but the ones that did transfer to Blender 2.80 correctly did. That was my findings by observing the .obj file on Notepad++.

Dope Sheet:
![image](https://user-images.githubusercontent.com/40968899/78844589-03557980-79bb-11ea-9343-933c0b6cd549.png)

Object Properties:
![image](https://user-images.githubusercontent.com/40968899/78844568-f33d9a00-79ba-11ea-9b84-6cec256f215e.png)

**Comment by tngreene** [comment]
What does it say on the Bone Properties tab? Blender has a confusing thing.

`Armature.002` is an Object with Bone data, like `Elevator` is an Object with Mesh data.

XPlane2Blender allows you to put X-Plane Keyframes on Objects (`Armature.002`, `ElevatorR` for instance.) And shows that on the Object Properties page (orange square).

XPlane2Blender allows you to put X-Plane Keyframes on Bones as well. Those are on the Bone properties page. Click on an individual bone and see.

**Comment by ArcticCoder1** [comment]
It’s the same thing. I’ve gone through all the children within the armature.

**Comment by tngreene** [comment]
Sorry, gotta check the basics.

Can you send me the 2.79 files and also them after they've been saved in 2.80? Just enough to replicate the problem, I don't need the whole thing.

**Comment by ArcticCoder1** [comment]
I will send it via email.

**Comment by tngreene** [comment]
The issue turned out to be related to not finding something in the UI, instead of something being wrong with Blender. Happens to the best of us!
