### ISSUE TITLE
280: Position of Lights Incorrect on Export

### ISSUE THREAD

**Issue by aussig** [X-Plane/XPlane2Blender#560]
I have a bit of an issue with the attached model when exporting to .obj - It has a basic mesh and two lights (I've omitted the textures as they aren't relevant). The mesh is exported perfectly but the lights are thrown up in the air above the model.

Sorry if this is my stupidity, I'm a novice with Blender and even less experienced with lights so happy to be pointed in the right direction if I need to fix something in the model.

For background info, I am the maintainer of OpenSceneryX and I am merging in a big set of third party objects to the library, but I need to make optimisations and changes to the models. I am trying to keep the original features, including the lights.

My workflow is this:
1. Import original `.obj` into AC3D using [this](http://www.inivis.com/forum/showthread.php?t=7032)
2. Export to AC3D native format `.ac`
3. Import `.ac` to Blender using [this](https://github.com/NikolaiVChr/Blender-AC3D/tree/2.80)
4. Clean up the object
5. Export to `.obj` using XPlane2Blender

I have also noticed that the named lights get turned into `VLIGHT`s during this process, but that's a separate issue.

[object.zip](https://github.com/X-Plane/XPlane2Blender/files/4597852/object.zip)

**Comment by tngreene** [comment]
Actually, having the lights be Default (or one of the other very old methods like FLASHING or STROBE aka VLIGHTs) does matter. They currently don't work well and their position is their literal position as reported by the object's location field, unlike other lights which take into account their parents position and animation. Try changing them to a named light or param light and see if that solves the issue.

There is also another potential alternative for you: Import your .obj into the Blender 2.49 tools, use the Blender 2.49 converter to get the model into Blender 2.79, save that, and simply open it in 2.80.

I don't know how much cleanup you have to do after import to make it into an XPlane2Blender ready project, but, that is one other option to consider. I've never used 2.49's importer but I know OpenSceneryX still has 2.49 models.

**Comment by tngreene** [comment]
See the comment here: https://github.com/X-Plane/XPlane2Blender/issues/370#issuecomment-594744845

**Comment by aussig** [comment]
Thanks Ted. I changed the light _Type_ to _Named_ and gave it the appropriate name _amb_street_light3_ and bingo!  All positioning is correct now, thank you for the pointer.

(Note I had a quick go at the `.obj` -> 2.49 -> 2.79 -> 2.82 route - wow 2.49 is a blast from the past - but the first model I tried errored at the convert 2.49 step. I might revisit this when I get some time but the AC3D route is working for me at the moment so I'll carry on with that for the mo).

Regarding the amount of clean-up needed - it can vary immensely from nothing, through just changing object origin position, through changing position and orientation, through re-texturing, through addition of LODs, through a complete remodel, and anything inbetween.  I just came across a 30cm bush with 1.5 million TRIs.  Yes, 1.5 million.  It was 99MB on disk, for something the user will hardly see. That's an extreme example but you get the gist!

**Comment by tngreene** [comment]
Thank you for all the work you do. OpenSceneryX is extremely important to X-Plane's scenery system and to me because its one of the extremely few things that the X-Plane artist community has decided on making Open Source. Its been very useful for making the converter at all!

I wish I understood why people make freeware with no intention of updating it making it payware and not release the .blend file. Maybe there should be more education about Creative Commons and things like the GPL if people are worried about credit given. Oh well. OpenSceneryX and the BD-5J microjet are great but that's limited and were made a while ago - they don't use the latest features like particles and some material stuff. Certainly weren't build from the ground up with collections in mind.

Thanks, and I'm glad it worked out! Be on the look out for Automatic Lights #183 soon enough.

**Comment by aussig** [comment]
And thank you too Ted, without the hundreds of hours you spend on XPlane2Blender, my job would be enormously harder. 

On the Creative Commons thing, it seems that for some there is a mindset that 'mine is mine' and it is hard to break out of that. There is a gradual movement for some library developers to contribute their work to OpenSceneryX, but on the other hand individual contributions have all but dried up recently, which is a little worrying.
