### ISSUE TITLE
280 4.0.0b2: "Copy to Selected" no longer working for some light type fields

### ISSUE THREAD

**Issue by aussig** [X-Plane/XPlane2Blender#578]
In 4.0.0b1, this works:

1. Select multiple lights
2. Select `Named` for the X-Plane light _Type_
3. Enter the name of a light into the light _Name_ (e.g. `amb_street_light3`)
4. Right-click both the _Type_ and _Name_ field values and choose `Copy to Selected`

In 4.0.0b1, the last step ensures all selected lights are set to `Named` with the correct light name.
In 4.0.0b2, the last step correctly sets the _Type_ field but not the _Name_ field.

I have also tested this other light types and their fields:

`Automatic` lights - the _Name_ field does not copy.
`Custom` lights - All fields copy across correctly (_Size_, _Texture Coordinates_, _Enable RGB_, _RGB Overrides_).
`Manual Param` lights - The _Name_ field does not copy, the _Parameters_ field does copy.

**Comment by tngreene** [comment]
Great find! This is related to #566! Will be fixed for the next version
