### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by joeycao2004** [X-Plane/XPlane2Blender#579]
I have just installed the addon with the help of the readme file, but I received an error:
<img width="657" alt="屏幕快照 2020-07-02 下午9 08 00" src="https://user-images.githubusercontent.com/57905565/86362658-32bd0f00-bca8-11ea-8e35-f829bec0213a.png">
Thanks in advance!

**Comment by tngreene** [comment]
Hi,

Try removing all versions, the installing the addon, and restart Blender. Something in that sentence will work.

If using the UI to remove the addon and any old versions of XPlane2Blender doesn't work, go to the addons folder itself and delete any folder with io_xplane2blender in the name

**Comment by joeycao2004** [comment]
Hello,
I have just reinstalled the plugin, and there is no install error any more. However, if I press the Export-X-Plane Objects button, and press "Export X-Plane Object" button in the File View window, I receive nothing. There is no error message, but there is no file saved either. Any idea why?

**Comment by tngreene** [comment]
That is odd. Does the button in the scene properties work instead of going through File > Export > X-Plane Object?

**Comment by tngreene** [comment]
Is it working for you?

**Comment by DWmFrancis** [comment]
If you mean; “Can I export objects which I have imported into Blender out to xPlane, the answer is; Yes. Having said that, I usually have to set the directory path to the texture image file manually, by editing the .obj file with textEdit and inserting; TEXTURE file_name.png, in order for the object to be visible in xPlane or PlaneMaker.

**Comment by joeycao2004** [comment]
Sorry for the late reply. It is yet to work for me, and the button in "Scene Properties" does not work for me as well. Pressed, nothing happened.

**Comment by joeycao2004** [comment]
I modeled the whole Autopilot myself, not importing it to Blender. Just made this, and now I'm trying to export it as a obj file. By the way, must the object be textured for exporting?

**Comment by tngreene** [comment]
For file paths: the texture file has to be where you say it will be, and X-Plane starts looking for that file relative to the OBJ.

If you have in your .obj file 

`TEXTURE my_texture.png`
Then X-Plane will say "I am looking for `my_texture.png` in the same folder the .obj is in"

If you have in your .obj file
`TEXTURE ../project_images/glass.png`
X-Plane will say "I am looking for `glass.png`. First I'll go up a folder, then I'll go down into `project_images` and look for the file in that folder.

>X-Plane starts looking for that texture file in the same folder that the .obj is in.

This way you can distribute your work to other people's computers without knowing where they keep their X-Plane installation folders!

Don't over think it, there are no fancy tricks

**Comment by tngreene** [comment]
To answer @joeycao2004 's question - 'You need a Blender material to make the exporter work (you don't have to customize it, just make sure every mesh has __a material__), but you don't need a texture file.

It'll show up as a matte grey in X-Plane but otherwise work fine.

**Comment by tngreene** [comment]
When you say "Doesn't work" what do you mean? No files are exported? There is an error telling you to save your .blend file first?"

Do you have a log you could past in?

**Comment by joeycao2004** [comment]
I receive no error, but no file exported as well.Where is the log file, I wonder? I’ll upload it if I can find it.

**Comment by tngreene** [comment]
Look for an internal text block in the text editor. You can also make it write the same content to a file to the same folder that the .blend file is in

**Comment by joeycao2004** [comment]
Hello!
I have solved the issue by reinstalling the plugin. Thank you for your help!
Quick Q, though, after finishing the manipulator and texturing, how can I export all objects to X-Plane, including the texture and manipulators? And what should I use for setting the cockpit.obj file (for manipulators)? Thanks!

**Comment by tngreene** [comment]
Yup, that is usually the problem and solution. I should include it in the instructions. Thanks!
