### ISSUE TITLE
Transferring Colors from Fusion 360 into xPlane

### ISSUE THREAD

**Issue by DWmFrancis** [X-Plane/XPlane2Blender#582]
Ted - I've been digging deeper into the question of how XPlane2Blender could support bringing colors into XPLane and it looks like the code already has some hooks to support it. It comes from Blender already handling the Wavefront.mtl file format.  Some of the K Factors use RGB values;

* The Ka statement specifies the ambient reflectivity using RGB values.
 
 "r g b" are the values for the red, green, and blue components of the 
color.  The g and b arguments are optional.  If only r is specified, 
then g, and b are assumed to be equal to r.  The r g b values are 
normally in the range of 0.0 to 1.0.  Values outside this range increase 
or decrease the reflectivity accordingly."

* The Kd statement specifies the diffuse reflectivity using RGB values.
 
 "r g b" are the values for the red, green, and blue components of the 
atmosphere.  The g and b arguments are optional.  If only r is 
specified, then g, and b are assumed to be equal to r.  The r g b values 
are normally in the range of 0.0 to 1.0.  Values outside this range 
increase or decrease the reflectivity accordingly.

* The Ks statement specifies the specular reflectivity using RGB values.
 
 "r g b" are the values for the red, green, and blue components of the 
atmosphere.  The g and b arguments are optional.  If only r is 
specified, then g, and b are assumed to be equal to r.  The r g b values 
are normally in the range of 0.0 to 1.0.  Values outside this range 
increase or decrease the reflectivity accordingly.

When Blender exports an .obj file it includes a companion .mtl file. For example;

ie: # Blender MTL File: 'None'
# Material Count: 1
newmtl Material
Ns 323.999994
Ka 1.000000 1.000000 1.000000
Kd 0.800000 0.800000 0.800000
Ks 0.500000 0.500000 0.500000
Ke 0.000000 0.000000 0.000000
Ni 1.450000
d 1.000000
illum 2

The Kd values (0.8 0.8 0.8) are RGB values which could be used to create a .png "paint chip" file for the albedo texture file. 

There is a lot of good information on the .mtl file format in this document;

http://paulbourke.net/dataformats/mtl/

If XPlane2Blender created a companion .png file for XPlane .obj8 objects, provided the file path as it already does, similar to way it can create a .mtl fie for Wavefront .obj files, it could provide an easy way to apply paint textures to XPlane objects.

**Comment by tngreene** [comment]
Changing the OBJ format and giving XPlane2Blender knowledge of how to handle Fusion 360 imports is completely out of scope for me and this project unfortunately.

It would be very useful indeed, but I'll never have the time to work on this. Fortunately, all these addons are open source letting you deeply extend whatever you need. Therefore I'm sorry to say, something like this will really never be made by me.

Best wishes,
Ted

**Comment by DWmFrancis** [comment]
Ted - You might want to follow along;

https://forums.x-plane.org/index.php?/forums/topic/220675-fusion-360-to-xplane-project/

http://thinkingofdesign.blogspot.com

**Comment by DWmFrancis** [comment]
Ted - Does xPlane2Blender have to have Albedo, Normal and LIT texture map files in order to export properly? I’m trying to export an object that has a chrome appearance. It looks shiny and reflective in one of the Blender windows, but doesn’t look like chrome in PlaneMaker or xPlane.

http://thinkingofdesign.blogspot.com

**Comment by tngreene** [comment]
It does not need a texture to export properly. Those texture file path boxes literally just write the string to the file. One day they might do more.

The work of making something look different is done primarily with the texture files, not with Blender settings

**Comment by DWmFrancis** [comment]
Ted -

Is there a built in or plug in way to create an xPlane compatible normal texture map with Blender?

-df

http://thinkingofdesign.blogspot.com
