### ISSUE TITLE
latest beta as of 07/9/20 - io_xplane2blender_4_0_0-beta_2-88_20200622173550

### ISSUE THREAD

**Issue by gregreenwood** [X-Plane/XPlane2Blender#583]
Installed add-on and got the following error when trying to check mark the addon for use.
![Screenshot from 2020-07-09 23-03-35](https://user-images.githubusercontent.com/8923433/87122243-58fb2580-c239-11ea-9a0c-57296855dc5e.jpg)
My machine Specs:
AMD Ryzen 5 w/32GB RAM, 500GB SSD
OS: LMint 19.3
Kernel: 5.3.0-62-generic GNU/Linux
Blender version: 2.79b

I installed the addon from the addon install file method and selected the downloaded zip file.
i have restarted Blender and get the same result.

Any Ideas?

**Comment by tngreene** [comment]
Thank you for your detailed computer specs - in this case the answer is simple. 4_0_0b2 requires Blender 2.80.

We're never going to develop a new version for Blender 2.79b unless it is work on the converter. Does your distro supply a later Blender version?

**Comment by gregreenwood** [comment]
glad it was simple.  updated my ppa.  loaded latest 2.83...  All good.
Thanks
GG

**Comment by tngreene** [comment]
Great news!
