### ISSUE TITLE
Reflections and Glass Effects

### ISSUE THREAD

**Issue by subabrain** [X-Plane/XPlane2Blender#584]
Hi there,

i have a simple Question:

how can i export "Reflection" or "Glass" Effects for a Airplane Model?

Thanks a lot!
Robert

**Comment by DWmFrancis** [comment]
Robert -

The amount of Reflectivity of an X-Plane object is set by the amount of blue in its NORMAL texture file and the amount of transparency is set by the Alpha of its TEXTURE file.

There is also a BLEND_GLASS directive which may be used.

Are you asking about how to include transparency and reflectivity in the X-Plane .obj8 file which xPlane2Blender creates from the Blender file?

-df 

http://thinkingofdesign.blogspot.com

**Comment by tngreene** [comment]
Hi, I'm closing this bug because it has been inactive for a long time. If you still have issues, please comment or file a new bug! I hope it is working for you! Thanks @DWmFrancis for answer this for me! It looks like he didn't have more questions after that!
