### ISSUE TITLE
Errors in RC1 Install with Blender 2.83 on MacOS

### ISSUE THREAD

**Issue by KarlLeclerc** [X-Plane/XPlane2Blender#589]
Hi Ted, Since you use GitHub to manage the project, I am repeating the essence of our discussion from the X-Plane.org forums in this post.

In a nutshell, the installation of the latest version (RC1) is generating errors in Blender and the add-on cannot be activated.

The instructions you provided (in a few places, Github, here, etc) is the process that I use for installation. To be sure, I started with a clean install of Blender 2.83.6, without any add-on (I only use yours). I installed 4.0.0 beta 2. No problem. The installation completes. I re-start Blender and I can make the add-on active with the check mark in the preference/add-on window. And it works: it exports my rather large Blender file without errors, and the helicopter works fine in X-Plane.

However, the same process does not work to install the RC1 zip file. I tested a few times to be sure. I first removed the beta 2 add-on by hitting the Remove button. Closed Blender. Re-started and used the exact same process to install the RC1 zip file (I tried the file here and the file you posted on X-Plane.org). It seems to install as the file is read and the add-on appears in the list. Closed and re-started Blender. However, when trying to make the RC1 add-on active by adding the check mark in the box, I only get errors.

The first screen capture shows that the process has loaded the RC1 add-on. The second screen capture shows the top of the error log. I hope this helps. In the mean time, I went back to beta 2.

![Installed](https://user-images.githubusercontent.com/30167203/93019105-edb83180-f5a2-11ea-9377-f6099f3d903f.jpg)

![Errors](https://user-images.githubusercontent.com/30167203/93019111-f4df3f80-f5a2-11ea-9435-319f65f487e5.jpg)

**Comment by tngreene** [comment]
Thank you for that screenshot! That is key! I think I've found the issue! Notice the text "io_xplane2blender-2"? The name has to be `io_xplane2blender`. With Python and Blender the addon folder name is extremely important. I'm not familiar with Mac, so I don't know why the folder name is getting a `-2` appended to it. Is it the way it deals with conflicting names?

Its very possible your total restart didn't actually give you such a clean slate as you though.
![image](https://user-images.githubusercontent.com/5393207/93029506-50ccb700-f5e9-11ea-973f-58f1123763c6.png)
For whatever reason, I have a strong feeling renaming that folder will solve your problems.

**Comment by KarlLeclerc** [comment]
Hi Ted,

Yes, I think that it was the problem. It seems that Blender in MacOS adds the -2 to the name if you try to add an add-on with a folder name previously used, even if the add-on was previously removed. Since I had previously installed beta 2, it would keep that folder name and only that beta 2 version would get installed in the io_xplane2blender folder; all other versions afterwards would get numbers appended to the folder name. Since your script uses absolute pathnames instead of relative pathnames, it would then result in a bunch of errors.

I did a bit of testing and simply changing the folder name (using the "mv" command) from:
/Users/.../Library/Application Support/Blender/2.83/scripts/addons/io_xplane2blender-X   to
/Users/.../Library/Application Support/Blender/2.83/scripts/addons/io_xplane2blender
did the trick. Upon restarting Blender, you can check mark the RC1 version of the add-on to make it active and it all works properly afterwards. You can also install Blender all over AND make sure that it is the first version of the add-on installed (subsequent installations fo subsequent versions will run into the same problem). Another (untested) option might be to find the folder __MACOSX (that is with two underscores at the beginning of the name) under the add-on folder structure and erase its content as it seems to hold the history of folder names.

Your current installation instructions are only correct for MacOS if it is the very first time or very first version of XP2B that gets installed. You may want to add a few lines for MacOS users in this regard. Or you could simply install your add-on in a different folder name for each different version numbers by adding the version number at the end.

In any case, thank you for your continued support. It took a bit of research, but with your help, I was able to install 4.0.0 RC1 and it seems to work as intended. Cheers.

Karl

**Comment by tngreene** [comment]
Thanks, for the detailed write up! I'll turn this into a documentation todo

**Comment by DWmFrancis** [comment]
Ted -

That’s what happens when you download more than one copy of a file.
The Finder automatically incrementally adds a dash number to every additional copy which is downloaded.

-df
