### ISSUE TITLE
Normal Metalness

### ISSUE THREAD

**Issue by miraoux** [X-Plane/XPlane2Blender#592]
In the previous version 4.0.0-alpha 4, there was a "Normal Metalness" field that was found in Material Properties, but it no longer appears in the new version. Please where is the field "Normal Metalness" in 4.0.0-rc.1. Thank you very much.

**Comment by airfightergr** [comment]
Still there it is.
![blender_metalness](https://user-images.githubusercontent.com/16308752/93499852-2c8c1580-f91c-11ea-832b-2bc90e79a672.jpg)

**Comment by arb65912** [comment]
![Normal Metalness 01](https://user-images.githubusercontent.com/16321070/93500078-d4382200-f8e1-11ea-9d48-267d1d55436a.jpg)
![Normal Metalness 02](https://user-images.githubusercontent.com/16321070/93500088-d7331280-f8e1-11ea-94cc-c4920d807d09.jpg)

**Comment by tngreene** [comment]
Thanks for the assist @airfightergr! @miraoux did that help?

**Comment by miraoux** [comment]
Thank you all for your responses.
I removed the addon, then reloaded again and now everything is ok, Normal metalness has reappeared in Material Properties /Draw Settings
It is a strange mystery, but now, I am happy!
My first tests with Blender 2.90 look good to me.
I'm sorry to have disturbed you.
Thanks to tngreene for his excellent work.

**Comment by tngreene** [comment]
No disturbance! I'm glad it worked out! File a new bug for any problem that confuses you!
