### ISSUE TITLE
Need advice. Please.

### ISSUE THREAD

**Issue by mixMugz** [X-Plane/XPlane2Blender#593]
Situation.
I have .OBJ file.
1. Import to AC3D
2. Edit
3. Export
All fine.

Another situation
1. Import to AC3D
2. Saved
3. Import AC3D to Blender
4. All looks fine
5. Edit
6. Export
Object rotated 90 degree around X axis.

I don't understand where is my mistake? And how i can fix it?

**Comment by airfightergr** [comment]
1. What filetype are you using to transfer from AC3D to blender?
2. AC3D and blender have the Y and Z axis flipped. In blender, when you are importing an object, there are some import option regarding scale, axis orientation, etc. Check those options.

**Comment by mixMugz** [comment]
1. I use AC3D file format. I don't know any other option to import OBJ to Blender
2. Ok, i will check. But can you tell me right way to correct settings?

**Comment by arb65912** [comment]
I might be mistaken as it was a long time ago but try to export ac3d to wavefront.obj format and then import wafront.obj to Blender.
Then you will need to rotate objects in Blender so they look like at attached screenshot.

![Orientation in Blender](https://user-images.githubusercontent.com/16321070/94082218-69e61c80-fdce-11ea-9a02-13696830921d.jpg)

**Comment by mixMugz** [comment]
Found where is problem
If i import Wavefront OBJ - each object rotated 90 degree
If i import AC3D - first level groups rotated 90 degree (object 0 rotation)
When i export first level group as root object - then object in x-plane rotated

**Comment by arb65912** [comment]
Glad to hear you figured it out! have fun!
