### ISSUE TITLE
Aileron Trim Not Being Set

### ISSUE THREAD

**Issue by ZotacAviation** [X-Plane/XPlane2Blender#597]
I've been able to set my rudder, rudder trim, elevators, elevators' trims, ailerons, and flaps perfectly, but I cannot find out why only my aileron trim stays at its begin position.

It is set to "sim/flightmodel/controls/ail_trim." I also have tried the other 3 datarefs just in case, but they did not change the outcome.

![image](https://user-images.githubusercontent.com/40968899/95135235-f373e380-0718-11eb-8676-6a470b84c5e9.png)
![image](https://user-images.githubusercontent.com/40968899/95135577-7d23b100-0719-11eb-8aa1-4c2a0e480897.png)
![image](https://user-images.githubusercontent.com/40968899/95135586-8280fb80-0719-11eb-9b1b-5356159ff97f.png)
![image](https://user-images.githubusercontent.com/40968899/95135610-8b71cd00-0719-11eb-97e7-131e74e748a5.png)

**Comment by ZotacAviation** [comment]
Here is the file with just the aileron and its trim surface.

[aileron.zip](https://github.com/X-Plane/XPlane2Blender/files/5330279/aileron.zip)

**Comment by tngreene** [comment]
I can say from just manually using the Dataref editor I got AileronLTrim to rotate
![image](https://user-images.githubusercontent.com/5393207/97490512-567f2180-1937-11eb-8012-23d947386452.png)

Is it a plane maker issue?

**Comment by DWmFrancis** [comment]
It looks like the trim tabs are operating backwards.
Is there a chance you have their signs reversed?

-df

**Comment by ZotacAviation** [comment]
Within the 23 days, I've been continuing on my aircraft ignoring the trim issue. I then sort of forgot about this and never realized when it resolved itself. Unfortunately, I don't know what it was that created the issue, but I guess I'll just be happy it worked out in the end.

> It looks like the trim tabs are operating backwards. Is there a chance you have their signs reversed?
Nope. Positive is full right and negative is full left, while this is the left aileron. The right side of the aileron moves, not the left.

**Comment by tngreene** [comment]
Great! I'm glad it resolve itself. If you remember why please right leave a comment!
