### ISSUE TITLE
Xplane object import wont show up

### ISSUE THREAD

**Issue by lolerilol** [X-Plane/XPlane2Blender#598]
Xplane object import won't show up do you have any fixes for this, it works to export though.
https://prnt.sc/uvorzl https://prnt.sc/uvos5k

I tried to use many versions of blender but none did work.

**Comment by tngreene** [comment]
From the README on the front page,

Introduction

This addon for Blender 2.80 and up makes it possible to export models made in Blender to the X-Plane object format (.obj). **Despite the name "XPlane2Blender", there is no import feature.**

Some other projects in the community exist that I have nothing to do with and there is also a longer pipeline involving 2.49's import files, and the 2.79 converter project. Another exporter for a different 3D program may have an importer, which could then export a .stl file, which Blender could read in, but you wouldn't have any animations or manipulators.

Sorry for the name, we get asked this a lot!
