### ISSUE TITLE
Objects transformed using "Object/Mirror" export with Normals Inside/Out

### ISSUE THREAD

**Issue by KarlLeclerc** [X-Plane/XPlane2Blender#600]
You can get the same results repeatedly by using the following process:
- Create an object (a shaped cylinder will make it obvious)
- Go to Edit Mode
- Select all vertices
- Move all vertices along the X-axis so that the point of origin is outside of the vertices
- Back to object mode
- Using the object mode menu, click on "Mirror", then "X-Global". This will create a mirror image of the original object on the X-axis (with the same point of origin)
- Save and Export to X-Plane by attaching to your favourite aircraft

The original object has the correct normals, while the mirrored object has its normals inside/out.

**Comment by KarlLeclerc** [comment]
For some reason, it posted twice.

**Comment by arb65912** [comment]
I think is happening in Blender, not exporter.
