### ISSUE TITLE
Cockpit Instruments Not Showing in the Simulator

### ISSUE THREAD

**Issue by ZotacAviation** [X-Plane/XPlane2Blender#602]
I've posted [a topic](https://forums.x-plane.org/index.php?/forums/topic/230625-unsolved-3d-panel-texture-wo-instruments/) on the XPlane.org Forums, but even two aircraft developers couldn't find a solution. This leads me to believe that maybe you might have some more information on this. The following contains some copied text from that topic but is more up to date.

Yeah, I know there's a lot of tutorials out there that are quite easy to follow, but I'm having an issue where none of these tutorials I've looked at show any sort of solution to an issue I'm having. The object appears grey or has the panel.png texture without the instruments, depending on if I set a panel.png texture to the object, which I hear isn't necessary. I've attached a file which has the copied object. I made sure the attributes are the same.

[Cockpit2.zip](https://github.com/X-Plane/XPlane2Blender/files/5469227/Cockpit2.zip)

**Comment by tngreene** [comment]
From following the conversation on the forum you appear to be on the right track. Some notes:
From the OBJ spec: https://developer.x-plane.com/?article=obj8-file-format-specification
```
Panel vs. object texture (default is object). Normally triangles are textured via the texture (and light overlay) named in the TEXTURE and TEXTURE_LIT attributes. When panel texture is turned on, the plane’s 2-d panel is used as a texture.  The lighting model for panel texturing may be “flat” (meaning no lighting calculations are provided) or “real” (meaning the full 3-d lighting system is used, matching the rest of the object); which lighting system is invoked depends on which attribute is used to select panel-texture drawing.
```

If you don't have a TEXTURE (or a valid one) you get a solid grey color. You (or someone in there) is correct, you don't specify the panel texture.

2 things to try:
1. Try adding `TEXTURE` to the header of the OBJ, just leave it blank. I'm forgetting if X-Plane has an issue in this case with the directive simply not being present
2, Try `TEXTURE cockpit_texture_path` to see if it wants a real texture

**Comment by ZotacAviation** [comment]
The following has been experimented after I had cleared the texture field in Blender for the cockpit.

`I
800
OBJ

GLOBAL_cockpit_lit
TEXTURE
NORMAL_METALNESS
GLOBAL_specular	1
POINT_COUNTS	8	0	0	18`
1. Grey cockpit, so I assume X-Plane doesn't have the issue. (Made sure there were no stray spaces after the attribute in case it mattered)
`I
800
OBJ

GLOBAL_cockpit_lit
TEXTURE Cockpit1.png
NORMAL_METALNESS
GLOBAL_specular	1
POINT_COUNTS	8	0	0	18`
2. Showed Cockpit1.png texture. No instruments.

**Comment by tngreene** [comment]
So I asked some people and they suggested that you look in X-Plane's Texture Browser > Render Targets. If your panel doesn't have anything there that's the first problem to solve

**Comment by airfightergr** [comment]
@ZotacAviation I've read the posts and there are 2 things to check. 

1. If you assigned the object as cockpit object, must follow the convention naming as **acfname_cockpit.obj** .
2. As someone wrote in the [topic](https://forums.x-plane.org/index.php?/forums/topic/230625-unsolved-3d-panel-texture-wo-instruments/&do=findComment&comment=2070554), you should have power on the electric bus and avionics turned on.

**Comment by tngreene** [comment]
Thanks for the comment @airfightergr ! (Actually X-Plane is smarter now and doesn't need the naming convention)

    Cockpit Objects. Before X-Plane 11.30 the cockpit object is a magical object found by file name (aircraft name_cockpit.obj). In     X-Plane 11.30 the cockpit object is just one among many “misc” objects in Plane-Maker, with the “cockpit object” check-box set.

    X-Plane and Plane-Maker will automatically upgrade/interpret old planes, so there’s no “todo” here or compatibility loss.

    This feature means that, starting with 11.30, you can now share a single cockpit object amongst multiple .acf files in the same folder. This means you can create multiple editions of your aircraft (e.g. for engine types) and not have to duplicate your cockpit .obj files.

https://developer.x-plane.com/2018/09/4k-panels-and-cockpit-objects-in-11-30/

**Comment by ZotacAviation** [comment]
A user in the XPlane.org Forums, Troopie, found that "ATTR_cockpit" was missing from the exported OBJ file that XP2B didn't include. [Link to post](https://forums.x-plane.org/index.php?/forums/topic/230625-unsolved-3d-panel-texture-wo-instruments/&page=2&tab=comments#comment-2072864)

**Comment by ZotacAviation** [comment]
I found out that I had a second material in the material properties that was overriding the actual material I wanted when I thought the one I wanted was the active one. Solved.

**Comment by tngreene** [comment]
Great! I'm glad to see it is working for you!
