### ISSUE TITLE
Decide Dataref Search Tool Defaults

### ISSUE THREAD

**Issue by der-On** [X-Plane/XPlane2Blender#61]
Datarefs should be displayed in an expandable tree view.

**Comment by tngreene** [comment]
After talking with Jim and Alex, here is the spec we came up with for this feature.

1. start typing a DR name in DR entry field
2. get a list of DRs. Each entry should show the metadata as well. Especially if it takes an index and is writable or not (for manipulators!)
3. select a DR by clicking it, or some UI element next to it. This preferably enters the data directly into the dataref field, but alternatively it could copy and paste it.
4. After selection or 10 seconds of inactivity, close this list

Search should behave like the DataRefEditor, but without the ||. Use of spaces is necessary.

We have a variety of implementation options:
- A collection of labels and buttons, similar to the custom properties in place
- We can copy the material selector ``template_list``
- We may be able to use the UV Map 
    
>    Whatever it is, it has to be fast, unobtrusive, and near by, yet also show all the search results.
>    Copy and paste, or the ability to click (fastest) on the data you want needs to exist. The UI should go back to how it was before the search list opened, this feature shouldn't wreck people's work spaces.
>    This should be done using the dataref itself instead of a new textfield property

**Comment by tngreene** [comment]
Ben says keep the |. As a refresher here is what it does

> A B|C D
> turns into
> (A && B) || (C && D)

**Comment by tngreene** [comment]
New Spec:
1. Button below Dataref Box "Open/Close Dataref Search"
2. User types* in DRE-like search filter, the list of datarefs is filtered
3. User clicks an operator next to item and Dataref Box is overwritten with results
4. Dataref Search closes automatically**
User can also click Close Dataref Search early and 

Options:
* Pre-populate search field with dataref box contents or not (seems possible), votes: 2 for prepolulation, 1 vote no, 1 vote idk
** Dataref Search closes automatically on selection or waits for explicit instruction: votes: 4 for closes automatically

**Comment by tngreene** [comment]
Also: If you have multiple datarefs, only one list can exist at a time. Opening one list closes a previous one. (This is due to try to control the statefulness of this whole pattern and being neat. The workflow is "don't spend much time with this UI component)

**Comment by tngreene** [comment]
Features:
- [ ] List of Datarefs.txt like files so people can search their plugins!

Polish:
- [ ] Don't show description
- [ ] Show columns of other meta data
- [ ] Decide on filter_name cleared when done with chosen dataref
- [ ] Decide on filter_name cleared when close search
- [ ] Should .blend file load with all dataref search window closed?
- [ ] Should a cached_filter_name be tied to each dataref?
- [ ] Ensure uniform look across

**Comment by tngreene** [comment]
Unit testing that the dataref search tool works sounds like a massive pain. If it isn't working, it will be immediately apparent, and won't break an OBJ.
