### ISSUE TITLE
Error Checking - Material assigned to Panel Texture

### ISSUE THREAD

**Issue by KarlLeclerc** [X-Plane/XPlane2Blender#616]
Hi Ted. We appreciate all the error checking that you have already built into XPlane2Blender. However, I ran into a good one recently while working on glass panel instruments using the panel texture:

If the material assigned to the panel texture normally used in the cockpit object is also used (by mistake) in another object file, it goes unnoticed by the exporter. However, once X-Plane tries to load the object file, it stops dead in its tracks with an error message stating that the object file is corrupted.

X-Plane is not precise in the description of the problem and it could take a while to hunt down.

I think that it would be a good improvement if that error was caught during the export process.

Thanks again. Cheers!

Karl

**Comment by tngreene** [comment]
I've seen this type of problem before: can you be more specific or even provide a small file that should get an error but doesn't?

**Comment by KarlLeclerc** [comment]
It requires a whole setup to reproduce: an .acf file, a Blender file creating a cockpit object file and another object (aircraft part) file. The cockpit object file must make use of the cockpit panel texture for its 3D instruments and have a few instruments/objects with their material assigned to the panel texture, just like you would when developing a glass cockpit aircraft. The aircraft part object file must (by mistake) have one of its part/object using the same material as the panel texture (which is not tolerated by X-Plane outside of the cockpit object file).

With a setup like that, the exporter won't catch the error, but X-Plane won't even load the aircraft. It will CTD with a vague error message only saying that the aircraft part object file is corrupted. Changing the material in the part file will fix it.

I am not willing to share my development files at this time for reasons that I am sure you understand. Maybe in private, a few months after it is released. That is months away if I keep up the pace without too many distractions :). In the mean time, I hope this helps. I do not depend on a fix as I was able to find the error without assistance from the exporter.

Thanks again for everything you do.

**Comment by tngreene** [comment]
I'm glad you were able to fix the error. Btw, "X-Plane error message is very vague. Here's the conditions which produce the error (the above) and here is what I'd like it to say" is very much content for an X-Plane bug!

http://dev.x-plane.com/support/bugreport.html
