### ISSUE TITLE
Beta 4.1.0 adds Global_cockpit_lit to all exported OBJ's without it being checked

### ISSUE THREAD

**Issue by Warmoer** [X-Plane/XPlane2Blender#617]
I upgraded to the 4.1.0 Beta yesterday, and have noted that all my exported OBJ's have the Global_cockpit_lit directive at the top while the Panel Texture Mode is set to default. I only picked this up when X-Plane started crashing when loading my aircraft and I started inspecting my OBJ's. These objects are also clearly marked as Aircraft(Part).
![XP2B_410B_1](https://user-images.githubusercontent.com/75410925/100970451-e7b56980-356f-11eb-85ad-f3989405443f.jpg)
![XP2B_410B_2](https://user-images.githubusercontent.com/75410925/100970453-e8e69680-356f-11eb-9626-c0a6b7ca0568.jpg)

**Comment by tngreene** [comment]
`GLOBAL_cockpit_lit` being added to every Aircraft and Cockpit type is okay, it only does something if you're actually in the cockpit object. This is apparently related to forward compatibility, so don't worry about performance.

The fact that you're reporting crashes is concerning. Are you sure that X-Plane crashes or doesn't crash based on whether or not GLOBAL_cockpit_lit is commented or uncommented out?

**Comment by Warmoer** [comment]
Hi Ted,
Thanks for the response. Good to know that the Global_cockpit_lit directive is save to remain in the obj files. I managed to track down the crash due to my incorrect handling of generic panels and how to include them under Misc Objects in Planemaker. The XPlane2Blender plugin had no part in the crashing - it was all user error.
