### ISSUE TITLE
Adding ATTR_manip_wheel to manipulators

### ISSUE THREAD

**Issue by todirbg** [X-Plane/XPlane2Blender#620]
Hi,
I am experiencing problems adding ATTR_manip_wheel to manipulators that do not support mouse wheel by default.
I am adding ATTR_manip_wheel as a Custom Animation Property in the Object Properties, but in the exported obj file it is added before the manipulator and does not work. Setting weight up to 100 does not make a difference. I also tried setting it in Custom Propeties.
![blender](https://user-images.githubusercontent.com/28814920/101385521-96d1a800-38c4-11eb-80c5-1823cd0c2db7.jpg)
Here is the patient https://github.com/todirbg/PZL-M-18
I am trying to add ATTR_manip_wheel to all drag rotate manipulators. Adding it manually in the obj works fine.

**Comment by tngreene** [comment]
Related #359. X-Plane doesn't currently allow the scroll wheel to be used with Drag Rotate. It may happen one day in the future!

As an aside, I'm looking forward to looking more into your PZL-M-18! Thank you for open sourcing your .blend file!

**Comment by tngreene** [comment]
Moved, thanks for reporting this!
