### ISSUE TITLE
Suggestions: Double Sided Normals and remark

### ISSUE THREAD

**Issue by Ulazygit** [X-Plane/XPlane2Blender#622]
1. (Double Sided Normals) I think SketchUp exporter can do this. Any chance of implementating it for the blender exporter?

2. (Remark) I currently input a remark (asset made by xxx) under custom material property but it would be nice if we could save a default comment added to each file so I don't have to do it per object.

**Comment by DWmFrancis** [comment]
I’m a big fan of this also, as it reduces the amount of geometry needed (by as much as 1/2) to create a part that is opaque from both sides.

~ df

**Comment by tngreene** [comment]
1. Double Sided Normals have actually been deprecated for a long while (a note in the spec says `this ensures the lighting queues on the back side of geometry are not wrong.  Again, the duplication of vertices is [better performance] than the attribute!` ) and won't be supported in XPlane2Blender
2. That's an interesting idea.... a custom copyright line. I'll make a feature request. Thanks!
