### ISSUE TITLE
Custom Export Locations w/Relative Paths

### ISSUE THREAD

**Issue by ZotacAviation** [X-Plane/XPlane2Blender#623]
Feature Suggestion: Custom Export Locations w/Relative Paths

When exporting all my objects, they all pop up in the same directory as the blend file. This means that the blend file has to be in the same directory you want your objects to go into, or you'd have to move every object to the objects folder every time you export. It's a bit impractical to have to remember to remove the blend file buried in the list of objects. It'd be nice to be able to export from a different location and not have to worry about accidentally uploading your blend file if you forget to remove it.

**Comment by tngreene** [comment]
Hi! This actually already exists. The name field can be an absolute or relative path and file name, or just a file name.

Suppose you have a Root Collection called `wing_l`
- With no name, you'd get `wing_l.obj` in the same directory
- With `objects/any_name_you_want.obj` you'd get an obj called `any_name_you_want.obj` in a folder called `objects`
- With `../any_name_you_want.obj` you'd get an obj called `any_name_you_want.obj` in the parent folder of the .blend file
- Also allowed but highly discouraged `C:/some/absolute/path/you/get/the/idea.obj`

Does this help?

**Comment by ZotacAviation** [comment]
Oh! My bad. That makes sense. Thanks for the guidance!

**Comment by tngreene** [comment]
No problem! Glad it worked out.
