### ISSUE TITLE
How do you export an object with specular 1.0?

### ISSUE THREAD

**Issue by Kreizler17** [X-Plane/XPlane2Blender#634]
I have been trying to export objects with a default specular value of 1.0. I’ve changed the material specularity to 1.0. But it always adds the specular 0.5 attribute. What am I doing wrong. I have to open the object file in a text editor and change it. It’s not that big of a deal but I would really like to know how to export it properly.

**Comment by tngreene** [comment]
Disable "use nodes" and use the old "Specular". I'm guessing they Specular property you're changing is actually the Principle Shader's. We don't use nodes yet

**Comment by Kreizler17** [comment]
That was it. Thanks a lot. I’ve been trying to figure that one out for quite a while. Appreciate it.
