### ISSUE TITLE
ATTR_light_level not working at export

### ISSUE THREAD

**Issue by kdkoronakis** [X-Plane/XPlane2Blender#646]
in latest exporter, ATTR_light_level seems that does not work with latest exporter version 4.10 beta 1. Any ideas ?

**Comment by tngreene** [comment]
Can you describe what "does not work" means? It doesn't export? There is the wrong data in there? It crashes? What happens?

**Comment by kdkoronakis** [comment]
it exports normally without any problems but in x-plane the change between day/night textures does not work. With ver 4.0 works fine.

**Comment by tngreene** [comment]
Can you post the screenshot of the material panel showing the values you set, and the output of OBJ content?

If you have a very complicated OBJ, you can make that easier to find by turning on debug info. To make it easier to find, set "Print Debug Info To Output, OBJ" at the bottom of the scene settings. Add a custom material property and use a comment "# Problem material". Search for "Problem Material in a text editor.

**Comment by kdkoronakis** [comment]
Thank you for your help. Here there are : 
![Screenshot 2021-03-02 at 17 09 01](https://user-images.githubusercontent.com/59867259/109668994-5a87ae00-7b7a-11eb-97df-c5036821a95e.jpg)
![Screenshot 2021-03-02 at 17 08 33](https://user-images.githubusercontent.com/59867259/109669016-61162580-7b7a-11eb-831f-bb87ce0437b9.jpg)
![Screenshot 2021-03-02 at 17 11 57](https://user-images.githubusercontent.com/59867259/109669045-670c0680-7b7a-11eb-87a8-778869631de5.jpg)

**Comment by kdkoronakis** [comment]
This is the start/end of the test object if you need more info please let me know. THANKS !
![Screenshot 2021-03-02 at 17 31 27](https://user-images.githubusercontent.com/59867259/109671927-2e216100-7b7d-11eb-8ba7-1db5c74d7263.jpg)
![Screenshot 2021-03-02 at 17 31 21](https://user-images.githubusercontent.com/59867259/109671962-36799c00-7b7d-11eb-8330-b0a8ec988d17.jpg)

**Comment by arb65912** [comment]
@tngreene  Ted, sorry for side question. Is there any approximate time frame for exporter to become released, not beta?
I see lot's of work is dedicated to importer but shouldn't exporter be finished first? 
many developers are using it for work while importer will be just for people who want to play around with someone else's work, right?

**Comment by tngreene** [comment]
@arb65912 Ben sets my priorities list and he says the importer is more important right now. Lips are sealed on why. Thank you for the inspiration to work harder for you all! You're my inspiration, and I'm sorry when the project slows down. Hang tight!

**Comment by tngreene** [comment]
@kdkoronakis , although the output of the OBJ looks correct, you really should be using that Override Light Level checkbox in the materials panel. When I suggested using a Custom Property I suggested using it for debugging purposes to help find the material if your .obj was very very large. (Custom Properties are a hack that aren't going to be around forever 😬 )

If this still isn't working I think the next step is to investigate your _LIT texture and the implementation of `plane/cockpit/Cpanel/fuel_light`. I always try replacing custom datarefs with `sim/graphics/animation/sin_wave_2` because its an easy to see effect.

**Comment by arb65912** [comment]
> @arb65912 Ben sets my priorities list and he says the importer is more important right now. Lips are sealed on why. Thank you for the inspiration to work harder for you all! You all are my inspiration, and I'm sorry when the project slows down. Hang tight!

Thank you very much Ted, I did not realized that Ben sets the priority list. Yes, mysterious indeed why. Thank you for clarifying things and as always thank you for a great job!!!!!

**Comment by kdkoronakis** [comment]
Hi Ted and thank you very much for your help.
I tried this method and works. However, when in a single object (a cockpit panel) there are 2 or more indicator lights and backlit on letters what I must do ? Do I have to make separate objects for each indicator light and also for panel backlit?
I'm asking this because the method you say above, can take 1 dataref for control.
Thanks again for your support.

**Comment by kdkoronakis** [comment]
Hi agan Ted,

I understood, ok. Problem solved !
Thank you VERY MUCH for your precious support.

Best Regards,
Kostas

**Comment by tngreene** [comment]
So others in a similar situation can learn: Can you share what the problem ended up being and what the solution was? You don't have to, but, its good for those searching later.

**Comment by kdkoronakis** [comment]
Sure Ted, 

Here is what I did 

In order to use multiple datarefs for light control at the same collection, you have to make different material groups, according to the lights you will use, and assign to each material a different dataref in "Override Light Level". In that way, you can control them separately.
I hope this helps.
If you need any more info, let me know.

Best Regards,
Kostas
