### ISSUE TITLE
'ValueError: path is on mount 'C:', start on mount 'E:' when exporting objects

### ISSUE THREAD

**Issue by ReverseGreen** [X-Plane/XPlane2Blender#648]
I am trying to export a basic building as an OBJ but I get an error saying that It can't find the file path, the texture is in the same folder as the OBJ and nothing is on my C drive?
 
![Screenshot (290)](https://user-images.githubusercontent.com/80170915/110216434-1a406c80-7ea7-11eb-99c1-bff4eda6c57e.png)
![Screenshot (295)](https://user-images.githubusercontent.com/80170915/110216439-1b719980-7ea7-11eb-9e95-efe135c5e681.png)
![Screenshot (296)](https://user-images.githubusercontent.com/80170915/110216442-1ca2c680-7ea7-11eb-90da-cb6cda655e2e.png)
![Screenshot (292)](https://user-images.githubusercontent.com/80170915/110216509-6f7c7e00-7ea7-11eb-8a44-bc8d2ed37f7e.png)

**Comment by airfightergr** [comment]
When you select textures, you should use the relative paths option at export.
![relativePath](https://user-images.githubusercontent.com/16308752/110221935-8f2b9a80-7ed7-11eb-917c-b551ee340185.jpg)

If the option is not visible, click the gear icon on the top right.

**Comment by tngreene** [comment]
Related to #332
