### ISSUE TITLE
Cannot enable plugin Blender 2.79.2

### ISSUE THREAD

**Issue by nubbix** [X-Plane/XPlane2Blender#657]
![2021-04-16_163151](https://user-images.githubusercontent.com/6438354/115042747-11927b80-9ed4-11eb-8ee1-a5f47394ccbd.jpg)

Keep getting this error message everytime I try to enable the add-on

Cheers
Tom

**Comment by Albannewcraft** [comment]
Goto C:/Users/tom/appdata(the file is invisible, you need to click on display on the top and check hide element to see the file)/roaming/blender fondation/Blender/2.79/script/addons and delete the file io_..........................................................................
now redoxload the file from github and installed it normally

**Comment by nubbix** [comment]
It was just a wrong version of Blender. Fixed by updating Blender

**Comment by tngreene** [comment]
Glad it works! The current supported version is listed on the front page as well for when it changes. Thanks @Albannewcraft for trying to assist!
