### ISSUE TITLE
Can't export, blender 2.92

### ISSUE THREAD

**Issue by Albannewcraft** [X-Plane/XPlane2Blender#658]
Hi i have install the plugin correctly but it's impossible to export to xplane 11 obj. When i click on export the windows close an my file dosen't export. Please help me.

**Comment by tngreene** [comment]
Right now only Blender 2.80-2.83 is officially supported. Some people have definitely used 2.90+ and had success. It seems spotty. Can you send me your 2.92 file or a small portion of it?

I'm guessing some default got changed and some people are affected and some are not. What OS do you have? If you start the file in Blender 2.83 and get it exporting there, does it work in 2.92?

**Comment by Albannewcraft** [comment]
> 
> 
> Right now only Blender 2.80-2.83 is officially supported. Some people have definitely used 2.90+ and had success. It seems spotty. Can you send me your 2.92 file or a small portion of it?
> 
> I'm guessing some default got changed and some people are affected and some are not. What OS do you have? If you start the file in Blender 2.83 and get it exporting there, does it work in 2.92?

Thanks for the fast reply ! I'm using windows 10 with the last update. I have try do dowgrade to 2.80 but it's not working. I have try tu unistall blender but not working. I don't no what is the problem.

**Comment by Albannewcraft** [comment]
[2.92.zip](https://github.com/X-Plane/XPlane2Blender/files/6345911/2.92.zip)

**Comment by todirbg** [comment]
Just to report - I am using 2.91 with 0 issues.

**Comment by Albannewcraft** [comment]
it work you can close the issues
