### ISSUE TITLE
Can't export

### ISSUE THREAD

**Issue by danielabadgamero** [X-Plane/XPlane2Blender#659]
Well, as the title says, I'm not able to export any objects to x-plane .obj format. That's what happens, in the screenshot. I have been able to export it once, but not more times after I closed blender and re-opened it. I tried multiple methods like uninstalling and reinstalling, downgrading drom 2.92 to 2.80 and then back to 2.83... All help is appreciated.
The screenshot says: see internal XPlane2Blender.log file, but I serached that file with the search function of my computer and it wasn't found absoulutely anywhere.
![imagen](https://user-images.githubusercontent.com/80352980/117571346-79507680-b0ce-11eb-952a-6dae091f76d7.png)

**Comment by DWmFrancis** [comment]
Daniel -

From the image you’ve posted, I can’t tell if your Cube object has a Material assigned to it.

Here’s how that looks on an aircraft I’m working on;

The red and black beach ball icon means the item in the list is a Material.

I call my panel material Panel to help me keep things organized in the list.

You can name the Material anything you like.



What are you trying to do exactly?

I see that you have an object named Cube, and its image in the Layout Window.

The mesh icon (the green triangle) is also visible. 

What material (the red and black beachball icon) is assigned to the mesh and what image is associated with that material?

Have you also UV unwrapped the object and positioned the image you want to use as the texture?

-df

**Comment by danielabadgamero** [comment]
Thank you for your help, I'm trying to develop an aircraft, a C172, to put it on sale and earn some money. Hopefully I'll end it and very hopefully someone buys it, but I don't think this is worth a cent haha. For the moment, I'm struggling to make the 3-D cockpit and that is an attempt for it. Here are some screenshots, if you can help me, that'd me awesome.
![imagen](https://user-images.githubusercontent.com/80352980/117576487-7feae800-b0e6-11eb-8dc9-c938114f17f2.png)
![imagen](https://user-images.githubusercontent.com/80352980/117576499-86795f80-b0e6-11eb-86ad-6b48f7083946.png)
![imagen](https://user-images.githubusercontent.com/80352980/117576506-8c6f4080-b0e6-11eb-9d53-ad4bb55b51ce.png)
![imagen](https://user-images.githubusercontent.com/80352980/117576512-91cc8b00-b0e6-11eb-8439-1c35757e4095.png)
Here they are. Thank you for your help and your fast answer is amazing.

**Comment by DWmFrancis** [comment]
Daniel -

I’ll do my best to offer some guidance.

BTW - There is a Facebook Group for Planemaker users here: https://www.facebook.com/groups/3219064364842275 <https://www.facebook.com/groups/3219064364842275>

It looks like you have succeeded in getting an image onto your cube.

How familiar are you with Blender?

-df

**Comment by DWmFrancis** [comment]
Daniel -

Do you have any experience with the X-Plane Planemaker software?

-df

**Comment by danielabadgamero** [comment]
Yes, with Plane maker I've already done the aircraft. I only have to do the 3-D cockpit now.
![imagen](https://user-images.githubusercontent.com/80352980/117578010-972cd400-b0ec-11eb-9565-5181ad7bd48b.png)

still have some work to do like learning how to tilt landing gear and work with the props a little bit. The fuselage also needs some work.

**Comment by DWmFrancis** [comment]
Daniel - 

So, you already have you own custom instrument panel layout done in Planemaker?

-df

**Comment by danielabadgamero** [comment]
Yes

**Comment by danielabadgamero** [comment]
![imagen](https://user-images.githubusercontent.com/80352980/117578160-42d62400-b0ed-11eb-82ef-0e41549f82ee.png)
i would like to learn how to put my own instruments since these ones are a little... how to say it... just not good

**Comment by danielabadgamero** [comment]
I would also like to learn how to put the cockpit in the cockpit lol, but this is about blender again
![imagen](https://user-images.githubusercontent.com/80352980/117578242-b7a95e00-b0ed-11eb-8440-d6440eacc982.png)

**Comment by danielabadgamero** [comment]
fully 3D would be best

**Comment by danielabadgamero** [comment]
so, any suggestions about the problem I had about not being able to export obj's? and do you know how can I make the 3d cockpit object in blender? thank you

**Comment by DWmFrancis** [comment]
OK - 

Basically you want to paint the 2D Planemaker instrument panel image onto the mesh of an object in Blender and export that to x-Plane with xplane2blender.

There is a way to do that using the Cockpit Features setting on the Materials Tab in Blender;




Your hierarchy in Blender will look something like this:



The name of the material doesn’t need to be Panel, but you do have to set the material's properties so that the Cockpit Feature of the material is set to Panel Texture.

I usually set the Collection to be a Root Collection rather than the panel object t be a Root Object.
You can do it either way, but don’t set an object to be Root in a Collection that is set to be Root.





BTW - The UV unwrapping is an important part of this process. Do you know how that works?

-df

**Comment by danielabadgamero** [comment]
First of all, what does UV stand for? I know how to unwrap but I don't know its purpose. Second, what should the hierarchy look like? I think you wanted to send a screenshot.

What you mean with this: "The name of the material doesn’t need to be Panel, but you do have to set the material's properties so that the Cockpit Feature of the material is set to Panel Texture." is that in this screenshot:

![imagen](https://user-images.githubusercontent.com/80352980/117578870-cb09f880-b0f0-11eb-8730-6f8c9c172981.png)

this has to be set like that?

**Comment by danielabadgamero** [comment]
well, fixed. the problem was that of the root collections, just had to uncheck "root collection", as you told me. Thank you very much for your help, you got me out of this blind alley. If you have time and want to help a young developer that would like to earn some money, could we continue talking via discord or any other way so that this issua can be closed and doesn't get too big? Please, only accept if you have enough time and want to. Thank you very much.

**Comment by DWmFrancis** [comment]
Daniel -

UV Unwrapping is the process of placing the image you want on a surface.

I usually go to UV Editing View in Blender - which will open another viewport.

You UV unwrap by;

1) Selecting an object in your model that you want to map an image texture onto. (Orange outline in the middle panel view below)
2) Switching from Object mode to Edit mode, which will reveal the mesh. (Orange in the next image down.)
3) Selecting the mesh in the Layout View. (Hit the A key for select ALL)
4) Selecting which projection style you want - I usually do Project From View. (The orientation of your object is important.)
5) Move to the UV window (on the left) and hit A to select ALL - which should reveal the unwrapped UV areas in Orange.
5) Resizing and scaling those UV unwrapped areas onto the portion of the image you want to have put there.

It’s a rather complex process unfortunately.

Note that the images you see in Blender are just for reference. They don’t actually flow thru Blender to X-Plane.

You might try doing this with a simple panel with just one instrument on it first.

What you are really doing is telling X-plane to use the 2D panel image that you created in Planemaker to paint the surface of the panel you made in Blender and where to place that image on your 3D model.

In your case, it's a cube. Some people just use a planar surface.

You should probably look at some YouTube videos on how to do UV unwrapping.

**Comment by danielabadgamero** [comment]
Thank you, and why was my cockpit the other way around, so what should be inside, was outside?

**Comment by DWmFrancis** [comment]
There are two sides to a surface.

With Cubes - there’s an inside and an outside.

You can select which one to map to, or reverse the direction of the normals - in the Mesh menu (I think)

-df

http://thinkingofdesign.blogspot.com

**Comment by danielabadgamero** [comment]
thank you, i will let you know if i have any other problems.

**Comment by xrotors** [comment]
Forgive me daniela,

I don’t think that flooding this particular Github subscription with tons of very - and I mean very - basic questions about 3D in general will help you out the right way with your willing to sell add-ons. It will more likely indispose everyone here instead. I would suggest you to get proper informations on websites like x-plane.org <http://x-plane.org/> instead, they got plenty of people willing to help, they have proper forums for that. Here we do offer some kind of help, but we more likely help out and support Ted and the guys with the Blender plugin.

My personal opinion though,
Xavier

**Comment by danielabadgamero** [comment]
Thank you, I actually was done with this, I already fixed the problem this question was about and no more

**Comment by DWmFrancis** [comment]
XRotors -

The problem was with the configuration of the xplane2blender export settings. (They allow you to set both the Collection and an object as the Root.)

I attempted to reply to Daniela directly as opposed to the group, but my email app may have failed me in that respect.

-df

http://thinkingofdesign.blogspot.com
