### ISSUE TITLE
Empty object in Planemaker - coming from Blander 2.83 - 

### ISSUE THREAD

**Issue by canadairman2002** [X-Plane/XPlane2Blender#661]
Hi,
I have Blender 2.83
Xplane2Blender 4.1.0. beta
Xplane 11

I have a solid ( fuselage ) in Blender.
I try to export it. No error message on Xplane2blender.log
When i try to open it in planemaker, it add the line but nothing visible.
Any idea ?
Thanks

**Comment by airfightergr** [comment]
Are normals outside? The position and scale of the object?

**Comment by canadairman2002** [comment]
im questionning myself. My model is a shell of 1mm thickness. I don't know if i only need to design a surface without thickness or not.

**Comment by tngreene** [comment]
What is the OBJ like? Did you try exporting  with Debug Info? Do you see any TRIS directives or VT directives or is just an empty file? I don't think the thickness should matter - I export planes all the time and they show up in X-Plane.

**Comment by airfightergr** [comment]
Not sure how the export script handles the scale, but I suggest once the model has the right dimension, apply scale. Show the face normals to be sure that they are facing outside.

**Comment by tngreene** [comment]
Scale taken into account as if the person has used "Apply > Apply Scale" (this is all in memory, it doesn't change anyone's object or mesh)

**Comment by tngreene** [comment]
Hmmmmm........ well, I'm guessing that TRIS directive is the thin line then. Have you seen the Debug Info yet? Scroll down to the bottom of the Scene Properties and you'll see the checkbox for it

**Comment by canadairman2002** [comment]
i did a test by importing my model with scale 1.0. So after , in blender, no need to scale again.
and it works :)

**Comment by tngreene** [comment]
Great, glad it worked out!

**Comment by tngreene** [comment]
And thank you @airfightergr for the triage support! Always helpful and always appreciated!

**Comment by canadairman2002** [comment]
thank you all for your support :)
