### ISSUE TITLE
backface culling in blender and not in xplane

### ISSUE THREAD

**Issue by subabrain** [X-Plane/XPlane2Blender#662]
Hello together,

i have the problem, that i have normal view in blender but its shown as flipped in xplane and the other way round ....

please help - i dont know further ...

thanks and greets!
Robert

**Comment by todirbg** [comment]
Check your normals and scale. If scale is negative number normals will look ok in blender, but will be reversed in x-plane

**Comment by tngreene** [comment]
@subabrain How'd it go 28 days later?

**Comment by subabrain** [comment]
hi tngreene,

hmm - not really - it always comes if i mirror some objects in blender ...

greets
Robert

**Comment by todirbg** [comment]
@subabrain  
That is the way blender mirrors. Just apply scale to your objects after mirror or if possible prefer mirror modifier. 

@tngreene 
Maybe xp2b can be made to use absolute scale in its calculations? Or this will create other issues?

**Comment by subabrain** [comment]
@todirbg thanks a lot - because of that i already used the mirror modifier ... how to apply scale? Just rescale?

thx a lot!

Greets
Robert

**Comment by todirbg** [comment]
@subabrain 
In Object mode select the object and press Ctrl+A to bring up the Apply menu, then select Scale.
Alternatively the Apply menu can be accessed from Object menu.

Contrary to what others may say I do not recommend applying other properties unless really needed.

**Comment by subabrain** [comment]
hi,

ok - i see - thank a lot!

Greets
Robert

**Comment by tngreene** [comment]
Seems like this bug is closed. Glad you got help!
