### ISSUE TITLE
import to blender with animation

### ISSUE THREAD

**Issue by subabrain** [X-Plane/XPlane2Blender#664]
Hello together,

im searching for a plugin to import the obj8 format in blender with animation data.
For example convert obj8 to fbx or similar.

if not i will try to make this by myself - i already modded some games ... so it will be possible i could do this ...

thanks and greets!
Robert

**Comment by DWmFrancis** [comment]
Robert -

You might take a look at OBJ8_convert, by Pasquale Croce, a.k.a Captain Spaulding.

I’ve been using it to peek under the hood of legacy x-Plane aircraft and it works very well.

As I recall, it extracts the animation axes along with the meshes.

-df

**Comment by subabrain** [comment]
Hi,

ok thanks - i will try ;)

Greets
Robert

**Comment by tngreene** [comment]
Also, we have a not-terrible importer in the works now. Check out the branch #610-importer. Basic animations are working, edge cases and optimizations aren't.

If you want to help, I instantly have something great you could work on!

**Comment by subabrain** [comment]
hi,

ok - thanks a lot!

maybe you have a link or something to get the code?

Greets
Robert

**Comment by tngreene** [comment]
Are you very familiar with GitHub and git? In the GitHub UI there is a way to look at the project's different branches. If you checkout the repo you'll be able to read and use the code.

I'm not sure where I left the code. I think there are a few small things you'll need to clean up first.
https://github.com/X-Plane/XPlane2Blender/tree/610-importer

The real key is in `io_xplane2blender/xplane_importer/xplane_imp_cmd_builder.py` and `xplane_imp_parser.py`. Also, to some extent `io_xplane2blender/tests/test_creation_helpers.py` which contains the functions and data structures that make the Blender data itself

**Comment by subabrain** [comment]
hi,

ok - thanks!

Greets
Robert

**Comment by subabrain** [comment]
hi,

sorry but i cannot find the import option for xplane (.obj) when installed the plugin ...

Greets
Robert

**Comment by subabrain** [comment]
hi there,

okay - i found now - but whats with the animations?

Greets
Robert

**Comment by tngreene** [comment]
Can you be more specific? What about the animations confuses you? btw: By the end of the day I'll have pushed a new commit that is much better code than I think what's currently online.

**Comment by subabrain** [comment]
hi,

sorry for disturbing you - but i get this error, when i try to load a X-Plane 11 .obj Model:

![2021-07-13 18_40_22-Window](https://user-images.githubusercontent.com/7425736/125494728-1e256c1d-fe7a-430a-8c52-deef14dff31a.png)

thanks and greets!
Robert

**Comment by tngreene** [comment]
Yes, that commit has a few problems in it. Try pulling the latest code from 665-dyn-anims-own-frame or replace the bad variable names that were in that commit.

I believe the problems were in build_mesh. If you really don't want to switch branches here's the function to copy and paste with.

```
    def build_mesh(self, vt_table: "VTTable") -> bpy.types.Mesh:
        mesh_idxes = vt_table.idxes[self.start_idx : self.start_idx + self.count]
        idx_mapping: Dict[int, int] = {}
        vertices: List[VT] = []

        for mesh_idx in mesh_idxes:
            if mesh_idx not in idx_mapping:
                idx_mapping[mesh_idx] = len(idx_mapping)
                vertices.append(vt_table.vertices[mesh_idx])

        # Thanks senderle, https://stackoverflow.com/a/22045226
        def chunk(it, size):
            it = iter(it)
            return iter(lambda: tuple(itertools.islice(it, size)), ())

        py_vertices = [(v.x, v.y, v.z) for v in vertices]
        py_faces: List[Tuple[int, int, int]] = [
            # We reverse the winding order to reverse the faces
            [idx_mapping[idx] for idx in face][::-1]
            for i, face in enumerate(chunk(mesh_idxes, 3))
        ]

        ob = test_creation_helpers.create_datablock_mesh(
            self.datablock_info,
            mesh_src=test_creation_helpers.From_PyData(py_vertices, [], py_faces,),
        )
        me = ob.data
        me.update(calc_edges=True)
        uv_layer = me.uv_layers[0]  # .new()

        i = 0
        if not me.validate(verbose=True):
            for face in py_faces:
                for idx in face:
                    me.vertices[idx].normal = (
                        vertices[idx].nx,
                        vertices[idx].ny,
                        vertices[idx].nz,
                    )
                    uv_layer.data[idx].uv = vertices[idx].s, vertices[idx].t
                    if "body" in ob.name:
                        # print(i, "uv", uv_layer.data[idx].uv)
                        pass
                    i += 1
        else:
            logger.error("Mesh was not valid, check console for more")

        test_creation_helpers.set_material(ob, "Material")
        return ob
```

But, 665-dyn-anims-own-frame is where development is currently happening for the next bit so keep an eye out there. The importer is very hot new code.

**Comment by subabrain** [comment]
hi,

ah ok - i see - thanks a lot!

Greets
Robert

**Comment by tngreene** [comment]
How'd it go?

**Comment by subabrain** [comment]
very nice :)

**Comment by tngreene** [comment]
Are you interested in working on specific features and issues? Where are you at?

**Comment by subabrain** [comment]
> Are you interested in working on specific features and issues? Where are you at?

Hi,

yes why not - but im not the best in python :/

but generally yes :)

Greets
Robert

**Comment by tngreene** [comment]
Sorry, we have nothing in the C++ department. If you have more questions of any kind including what to get started on in Python, please let me nkow
