### ISSUE TITLE
Issue Changing colors when animating with bones

### ISSUE THREAD

**Issue by haibaadel** [X-Plane/XPlane2Blender#671]
Hi,

     When animating with bones the fields highlighted in the image below doesn't change colors like when using empties.

<img src="https://i.imgur.com/DS1YY07.png" alt="Bone Animation">

Regards

**Comment by tngreene** [comment]
Yes, this is a known problem. I have no idea why it doesn't work sadly. Thanks for reaching out!

**Comment by haibaadel** [comment]
Sade to hear this, anyway, it works fine.
