### ISSUE TITLE
Xplane2Blender latest versions no import

### ISSUE THREAD

**Issue by florincoter** [X-Plane/XPlane2Blender#674]
Hello,
Today, 9 Oct 2021. I have installed the latest versions of Blender and Xplane2Blender, imported the XP2B addon into Blender,, restarted the computer.
There is no XPlane import menu in Blender, only export.
I could not find any info stating that the XP2B is in fact B2XP only. 

Please illuminate.

Thank you,
Florin.

**Comment by DWmFrancis** [comment]
Florin -

There is currently no feature in XPlane2Blender to import existing xPlane object files, however, you may use Captain Spaulding’s .obj8 converter to turn .obj8 files into Wavefront .obj files which *can* be imported into Blender.

I use this regularly to study other aircraft creator’s designs.

https://forums.x-pilot.com/files/file/1290-obj8-to-wavefront-obj-converter/ <https://forums.x-pilot.com/files/file/1290-obj8-to-wavefront-obj-converter/>

-df

**Comment by florincoter** [comment]
Thank you.

 

 

Dr. Florin Coter

9A Baal Shem Tov St., Haifa 3372427, ISRAEL

Res.: +972 (4) 8640337

Cell.: +972 (54) 4FLORIN

Web:  <http://www.florincoter.wix.com/fcph> www.florincoter.wix.com/fcph

 

"When you feel the breeze on your cheek, you know that is God. When there is no breeze, you should run." (A Buddhist Monk)

"Don't practice untill you get it right. Practice until you cannot get it wrong." (Unknown)

**Comment by DWmFrancis** [comment]
You are welcome.

Many things about both XPlane2Blender and using Blender to create aircraft are neither obvious nor intuitive. You might consider joining the Plane Maker user group on Facebook.

-df
