### ISSUE TITLE
io_xplane2blender_4_1_0-beta_1-101_20201117225215.zip

### ISSUE THREAD

**Issue by Swiss003** [X-Plane/XPlane2Blender#691]
If I want to export multiple objects, he only exports one object help plssss

**Comment by DWmFrancis** [comment]
Have you grouped your objects into collections and set the preferences to export them as one root collection?

-df

http://thinkingofdesign.blogspot.com

**Comment by Swiss003** [comment]
No can you show me how to do that
Op zo 6 feb. 2022 om 16:05 schreef DWmFrancis ***@***.***>

> Have you grouped your objects into collections and set the preferences to
> export them as one root collection?
>
> -df
>
> http://thinkingofdesign.blogspot.com
>

**Comment by DWmFrancis** [comment]
How much experience do you have with Blender?

-df

http://thinkingofdesign.blogspot.com
