### ISSUE TITLE
Export settings: orientation

### ISSUE THREAD

**Issue by pl4sma2389** [X-Plane/XPlane2Blender#692]
Hello,
I'm developing some aircraft for both X-Plane and MSFS. I can deal with the material conversions, but one thing that is very difficult is the default aircraft model forward direction.
In MSFS, the aircraft model points towards the negative Y direction in Blender, but in X-Plane, the aircraft model points toward the positive Y direction.
I cannot find an easy way to solve this issue in my models. I tried selecting and rotating everything around the Z axis to face it in the correct direction, but that screwed up the animations. I then tried parenting everything to an empty and then rotating the empty, but that also screwed up the animations.
Would it be possible to have an option in the Export settings to rotate the model 180 about the Blender default Z axis, or would it be easier for each individual aircraft creator to redo the animations, or is there some easy way of doing this that I am missing?
Thanks.

**Comment by bsupnik** [comment]
You can rotate the object on import in Plane-Maker.
