### ISSUE TITLE
XPlane2Blender Version Compatabilty & Bug Report

### ISSUE THREAD

**Issue by artcore-c** [X-Plane/XPlane2Blender#693]
First I Sincerely Thank the efforts here because I've been trying to import .OBJ8 into Blender for some time with no success, the MacOS terminal conversion cannot parse? however I did enjoy limited results earlier this evening that I am Both elated that I was able to import most of the .obj parts of a favorite aircraft using Blender 2.83.20 release candidate with XPlane2Blender 4.2.0 alpha alpha alpha! Unfortunately however Blender crashed and and the add-on was somehow removed from list of installed add-ons? All subsequent attempts to reinstall fail, downloading both the add-on and Blender 2.83 anew and still won't install, nothing happens selecting the .zip? Python errors with 2.93 and above the add-on installs but cannot be switched on checking the box. 4.1.0 installs with Blender 2.93.9 release candidate but is export only. I wonder if the problem with 4.2.0 is some conflict with other add-ons? or Python scripting errors? I don't know but would really love to see it working agin soon!

**Comment by lehthanis** [comment]
Try the fix I posted to issue 689 https://github.com/X-Plane/XPlane2Blender/issues/689

**Comment by bsupnik** [comment]
This is probably fixed in 4.2.0rc2.  If not ,please post the pythonerrors.
