### ISSUE TITLE
Blender 3.1 and release 4.1.0 beta 2 compatibility

### ISSUE THREAD

**Issue by xrotors** [X-Plane/XPlane2Blender#694]
On upgrading to Blender 3.1 from Blender 3.0 the plugin was still there, active, but not visible in the sidebar.
Removing the plugin and attempting a reinstall caused the plugin to unactivate and return this message...

<img width="904" alt="Schermata 2022-03-10 alle 08 56 41" src="https://user-images.githubusercontent.com/57137483/157615170-f15be40e-2a30-4ee9-9c3e-93f12e91d69f.png">

**Comment by xrotors** [comment]
Same happens with 4.2.0 alpha alpha alpha release...

<img width="902" alt="Schermata 2022-03-10 alle 09 02 45" src="https://user-images.githubusercontent.com/57137483/157615775-3e254e41-8ac3-4a28-b000-e0059a51f542.png">

**Comment by xrotors** [comment]
macOS 10.15.7 (19H2)
Darwin 19.6.0

**Comment by lehthanis** [comment]
Try the fix I listed in issue 689. https://github.com/X-Plane/XPlane2Blender/issues/689
The problem seems to be python version related not blender version related. Perhaps the python version shipped with 3.1 is higher.

**Comment by xrotors** [comment]
Today I tried Blender 3.1 with the latest XP2B plugin (4.1.0b2).
Same issue.

**Comment by bsupnik** [comment]
This is fixed in 4.2.
