### ISSUE TITLE
XPlane2Blender version 4.2.0 alpha offers the option to export to XPlane OBJ, but does not work for blender 2.79, 2.83 and 3.0

### ISSUE THREAD

**Issue by stradiotto** [X-Plane/XPlane2Blender#695]
1) I know it's in alpha version. So, I apologize if this reclaim has an obvious solution: Wait for the alpha version of XPlane2Blender to evolve.

2) I just installed the XPlane2Blender plug-in from .zip files into Blender 2.79 (recomended by XPlane), 2.83 (Might be 2.80 as recomended by you, but lately I could find if here [https://download.blender.org/release/Blender2.80/]), and 3.0, but in none of them Blender could export the XPlane 3D model. The app could not even write to the chosen target file.

3) I believe that - as it is the alpha version - the first objective was just to create the Export menu item, as in every application project.

4) Is there a way to know when this export module will be ready to use? Some project milestone?

Thanks for your attention. We are waiting this module anxiously.

César R K Stradiotto

**Comment by bsupnik** [comment]
This is fixed in 4.2.0rc2.
