### ISSUE TITLE
I can't export

### ISSUE THREAD

**Issue by gbcarvalho2022** [X-Plane/XPlane2Blender#696]
I'm using Blender 3.1.0 with io_xplane2blender_4_1_0-rc_1-104_20220317232939, however, when exporting the project, it just doesn't export, it doesn't generate the file when I click "Export X-Plane Object"
Can anybody help me?

**Comment by yeahyeahwhatever234** [comment]
Same here

**Comment by bsupnik** [comment]
The GitHub issue tracker for XPlane2Blender is meant for reporting bugs in the exporter itself, not for help using the add-on. You will need to get help on an x-plane forum for basic usage problems.
