### ISSUE TITLE
X-Plane (.obj) importer not present after 4_2_0-alpha_1

### ISSUE THREAD

**Issue by xrotors** [X-Plane/XPlane2Blender#698]
The nice X-Plane .obj import feature seems missing from the latest releases, both 3.0.1 and following.

**Comment by xrotors** [comment]
Ok, I understood the importer is experimental only in 4.2.0 alpha 1

**Comment by bsupnik** [comment]
OBJ import is not part of the main release stream of exporter releases.  It will be included in a future update.
