### ISSUE TITLE
Version missmatch

### ISSUE THREAD

**Issue by haibaadel** [X-Plane/XPlane2Blender#700]
Greetings awesome people,

      Is this Version 4.1.0 - RC2 or Version 4.2.0?

I downloaded this:-

![Capture](https://user-images.githubusercontent.com/12466153/168698885-b9a183b8-295c-4a6d-b4a3-c610b19f373b.JPG)

      
Check the image below

![Capture](https://user-images.githubusercontent.com/12466153/168698363-80ba575e-ca45-4781-adde-b2b098e1b0e7.JPG)

Thanks and regards

**Comment by bsupnik** [comment]
Fixed - thanks for catching this.
