### ISSUE TITLE
 transparent texture on the x-plane

### ISSUE THREAD

**Issue by gbcarvalho2022** [X-Plane/XPlane2Blender#702]
Dear friends. I'm new to the world of X-Plane and I'm developing objects for the x-plane using blender.

I've already managed to create basic objects, such as houses, buildings, in "box" formats, all in blender and exported to x-plane.

recently I'm modeling an object, other than in the box format, which faces should be seen on both sides in the x-plane, but with no success.
even inserting textures on both faces in Blender, when exporting to the x-plane, the texture only appears on one face, with the object being transparent on the opposite face.

can anyone tell me what i'm doing wrong?

I attached the image of an obj created in blender, being viewed in WED. you can see that in the face that I left without texture, you can't see the other faces of the cube from the inside, the obj appears transparent

I'm using the X-plane plugin io_xplane2blender ver. 4.1.0 with Blender ver. 3.1.0 and Windows 10 PRO

thanks for help

![sample cube](https://user-images.githubusercontent.com/102762517/174809554-787438b1-1de0-432b-98eb-341649456576.png)

**Comment by bsupnik** [comment]
The GitHub Issue Tracker for xplane2blender is for reporting bugs in the export add-on itself; to get basic help with using the add-on you will need to find help in an X-Plane forum.
