### ISSUE TITLE
Export Issue

### ISSUE THREAD

**Issue by P1lotPaul** [X-Plane/XPlane2Blender#705]
Hello,
I am new to Planemaker and Blender. I installed the addon (Version 4.1.0) for Blender (Version 2.80). but when I try to export something in the X-Plane .obj format either there is no file or there is a .blend file.

Thanks for any kind of help

Paul

**Comment by bsupnik** [comment]
The GitHub Issue Tracker for xplane2blender is for reporting bugs in the export add-on itself; to get basic help with using the add-on you will need to find help in an X-Plane forum.
