### ISSUE TITLE
a single ATTR_cockpit_device property in Blender....  outputs two device entries in the exported OBJ

### ISSUE THREAD

**Issue by tkyler** [X-Plane/XPlane2Blender#707]
a one polygon export (quad),   where the poly is set to ATTR_cockpit_device for the Garmin 530...results in TWO directives in the OBJ, where the 2nd directive is the GNS430 and overrides the single, 'intended' 530 screen desired.  Expect only one entry in the OBJ.  Also happens for other ATTR_cockpit_devices

Screenshot shows Blender setup and resulting exported OBJ.

![export_issue](https://user-images.githubusercontent.com/399085/190871198-a280a39e-d5c8-4e81-af48-cada57012953.png)

**Comment by tkyler** [comment]
[Duplicate_ATTR_cockpits_debug.blend.zip](https://github.com/X-Plane/XPlane2Blender/files/10831902/Duplicate_ATTR_cockpits_debug.blend.zip)

**Comment by bsupnik** [comment]
This is not a bug. The attached object has a custom ATTR device and a material ATTR device, so the exporter exports both.

This is silly and custom attributes are a way to stub your toe, but it's definitely not a design goal to strip custom attributes.
