### ISSUE TITLE
Xplane2blender 4.2 and Blender 3.3 LTS errors

### ISSUE THREAD

**Issue by uffdaken** [X-Plane/XPlane2Blender#708]
Would be nice to get Xplane2blender 4.2  to work with Blender 3.3 LTS since this will be supported for two years. Hope the image with the errors shows up ok. Take care.  

![X-Plane2blender 4 2 errors](https://user-images.githubusercontent.com/51299709/192111227-1324082f-50c5-43fd-bf3a-12250847abf2.png)

**Comment by bsupnik** [comment]
Exactly what version of the exporter did you see this with? This was issue #689 and was fixed in 4.2.0rc2.
