### ISSUE TITLE
Xplane2blender 4.2 and Blender 3.3 LTS

### ISSUE THREAD

**Issue by uffdaken** [X-Plane/XPlane2Blender#718]
After updating to Python 3.10.2, I got xplane2blender 4.2alpha to install in Blender 3.3 LTS, but the importer and exporter do not show up in the import and export list.

**Comment by bsupnik** [comment]
Please try 4.2.0rc2.

**Comment by uffdaken** [comment]
Hi Ben, right now the only setup that work with the Export and Import is Blender 3.0.1 and XPlane2Blender 4.2_Alpha -4028. Only some .obj will import. Still working on the correct workflow for exporting .obj to X-Plane 12. On some imports, I get error messages, but it still loads the .obj file.  I have tried XPlane2Blender 4.2 rc2, but it will not install in Blender 3.3. If I try to install install in Blender 3.0, I might get only the export listing.
