### ISSUE TITLE
Cannot use candela (cd) as intensity unit

### ISSUE THREAD

**Issue by xrotors** [X-Plane/XPlane2Blender#720]
When attempting to set **candela (cd)** as intensity unit for a light source (eg. airplane_nav_pm or bb as param for X-plane 12) the exporter stops and xplane2blender.log returns _ERROR: Parameter 4 (250cd) of nav left is not a number._

**Comment by xrotors** [comment]
For your knowledge, these are the params I am trying to export with the _airplane_nav_pm_ light

`0 1 0 0 250cd 1.0 -0.01 -0.01 0.4`

**Comment by xrotors** [comment]
I seen there's a commit on this topic, but apparently is not working on 4.2.0-rc2 69f1466cf1cf2061205e1b02797c09d360c20f8d

**Comment by bsupnik** [comment]
Please post a picture of your light properties inspector so we can see how you have set up the photometric nav light. PLease use airplane_nav_pm as referred in the previous comment.

**Comment by xrotors** [comment]
<img width="655" alt="immagine" src="https://user-images.githubusercontent.com/57137483/216643347-b13a3c00-229e-4797-b97a-566bf3599357.png">

**Comment by xrotors** [comment]
I cannot set it to `250cd` but I have to use just the number, then I have to edit the .obj file manually.

**Comment by bsupnik** [comment]
Don't use the deprecated manual param light mode. Set the light mode to automatic; when you pick a photometric light you'll get an "intensity" parameter.  Set 250 and don't suffix CD (intensity is always cd) and it will work./

**Comment by xrotors** [comment]
Thanks, it actually works for everything except strobe lights.
