### ISSUE TITLE
Problem with datarefs

### ISSUE THREAD

**Issue by Stormriderplayz** [X-Plane/XPlane2Blender#721]
The seem to be a problem with the datarefs for x-plane 11, because I enter datarefs, they move in planemaker, but don't work in x-plane 11

some help will be needed please

![Screenshot (2919)](https://user-images.githubusercontent.com/112338323/216627680-48df57a2-b271-4212-a879-d7209c7fc794.png)
![Screenshot (2920)](https://user-images.githubusercontent.com/112338323/216627701-c654dca0-a6b8-45c6-811e-69cc44a40b56.png)
![Screenshot (2921)](https://user-images.githubusercontent.com/112338323/216627709-fa7c8edc-043c-422c-bf89-3fbdb0f9a772.png)

**Comment by bsupnik** [comment]
Hi,
The Github issue tracker for XPlane2Blender is for reporting bugs with the exporter itself. You will need to get help on an x-plane forum for problems setting up basic animation.
