### ISSUE TITLE
no weather map

### ISSUE THREAD

**Issue by fsspn** [X-Plane/XPlane2Blender#727]
I miss an input field similar to TEXTURES for the weather map. If a weather map is used, the .obj-file has to be manipulated after exporting from blender (every time), a boring procedure. Can you change that?
Greetings AK

**Comment by bsupnik** [comment]
What is the exact OBJ directive name that you are looking to specify?

**Comment by fsspn** [comment]
Sorry, maybe I have a translation problem, what do you mean with directive?

 

In blender I can specify several bitmaps for texturing. Since XP11 (I think) there is an additional possibility in obj-files to add a map for weather situations that brings snow, water, rain and so on onto surfaces.

It would be great, if the weather map could be automatically included into the obj-file. For this, there should be a field in blender to specify the weather map’s name similar to the other bitmaps mentioned.

 

Andreas

 

 

I

800

OBJ

 

TEXTURE             ColorMap.dds

TEXTURE_LIT     ColorMap_LIT.dds

TEXTURE_NORMAL        ColorMap_NML.png

WEATHER WinterMap.png

NORMAL_METALNESS

GLOBAL_specular 1

…            

 

 

 

Von: bsupnik ***@***.***> 
Gesendet: Freitag, 8. September 2023 18:07
An: X-Plane/XPlane2Blender ***@***.***>
Cc: A. Koerner ***@***.***>; Author ***@***.***>
Betreff: Re: [X-Plane/XPlane2Blender] no weather map (Issue #727)

 

What is the exact OBJ directive name that you are looking to specify?
