### ISSUE TITLE
Datarefs/Animations are not exported

### ISSUE THREAD

**Issue by Riride** [X-Plane/XPlane2Blender#731]
Hi!

No amount of reinstalling and/or using older versions of Blender fixed the issue.

I made each control surface an independent root object. I parented each one to an empty, animated the empty, baked the actions to the objects and set up the datarefs and keyframes, then I deleted the unused empties. The animations run properly in Blender. I exported the root objects to the airplane directory.

![Sans titre](https://github.com/X-Plane/XPlane2Blender/assets/145106844/63f30ea2-8c40-40c3-a806-5ccac3e51939)

In Plane Maker, the control surfaces are present, but they remain still in neutral position for the elevators, rudder and ailerons, and up for the flaps.

Here's what it looks like in Plane Maker (the .obj's are white):

![image](https://github.com/X-Plane/XPlane2Blender/assets/145106844/00f4423e-6900-48a3-8ae0-7e61f0833bd4)

![image](https://github.com/X-Plane/XPlane2Blender/assets/145106844/4ae95eaf-c201-4f11-8a7c-0314af3a4be7)

In the actual sim the controls surfaces don't move either.

It's also the case for cockpit switches, handles etc.

Has that already been encountered before?

Thank you guys a lot

I use Blender 3.3.9, XPlane2Blender v4.2.0 rc3 and X-Plane 12.

**Comment by DWmFrancis** [comment]
Have you looked at the aircraft's object file to see if the animation commands are just not there or have bad values?

**Comment by Riride** [comment]
Sorry, found my error and forgot to update. The issue was caused by manually exporting each object instead of pressing "Export OBJs" in scene properties.

**Comment by Im-Unknown-now** [comment]
I have the same problem, but it only happens when I use bones(this hasn't happened before). I use Bledner 4.5, Xplane2Bledner 4.4.0, and X-plane 11
