### ISSUE TITLE
Override light level: Prefer to have that tied to object, rather than material

### ISSUE THREAD

**Issue by danklaue** [X-Plane/XPlane2Blender#77]
I find working with "Override Light Level" as a material property quite cumbersome.  If, for instance, a cockpit is made that uses LIT textures to illuminate buttons, each button must have its own material.  This becomes difficult to manage in large cockpits.

I also notice that sometimes materials don't seem to "close" their properties properly; setting a manipulator surface to "invisible," for instance, has caused other objects to become invisible as well.  My solution has been to change the "weight" of the affected objects, so that they are drawn before the invisible objects are drawn. 

But this lack of reliable closure of materials properties has also affected LIT texture usage, making its implementation unreliable, confusing, and time-consuming.

**Comment by tngreene** [comment]
Finally closed with #663
